"""Curated Wikipelago article pool: (Wikipedia title, category)."""

ENTERTAINMENT_ARTICLE_POOL: list[tuple[str, str]] = [
    ('Elliot Page', 'video_games'),
    ('Jon Bernthal', 'video_games'),
    ('Grand Theft Auto V', 'video_games'),
    ("Assassin's Creed", 'video_games'),
    ('Hayden Panettiere', 'video_games'),
    ('IShowSpeed', 'video_games'),
    ('Call of Duty', 'video_games'),
    ('Intelligence artificielle', 'video_games'),
    ('Minka Kelly', 'video_games'),
    ('Grand Theft Auto VI', 'video_games'),
    ('Yvonne Strahovski', 'video_games'),
    ('Richard Darbois', 'video_games'),
    ('Lucien Jean-Baptiste', 'video_games'),
    ('Grand Theft Auto', 'video_games'),
    ('Clair Obscur: Expedition 33', 'video_games'),
    ('Minecraft', 'video_games'),
    ('Grand Theft Auto: San Andreas', 'video_games'),
    ('Hans Zimmer', 'video_games'),
    ('Dorothée Pousséo', 'video_games'),
    ('Donald Reignoux', 'video_games'),
    ('The Amazing Digital Circus', 'video_games'),
    ('Squeezie', 'video_games'),
    ('Céline Monsarrat', 'video_games'),
    ('Lena Headey', 'video_games'),
    ('Pokémon', 'video_games'),
    ('Emmanuel Curtil', 'video_games'),
    ('Jensen Ackles', 'video_games'),
    ('Kiefer Sutherland', 'video_games'),
    ('Destiny Eleven', 'video_games'),
    ('Nathan Fillion', 'video_games'),
    ('PlayStation 5', 'video_games'),
    ('Bernard Alane', 'video_games'),
    ('Jean Pormanove', 'video_games'),
    ('Ron Perlman', 'video_games'),
    ('Will Yun Lee', 'video_games'),
    ('Adeline Chetail', 'video_games'),
    ('Lana et Lilly Wachowski', 'video_games'),
    ('Meccha Chameleon', 'video_games'),
    ('Palworld', 'video_games'),
    ('Jacques Frantz', 'video_games'),
    ('Adrien Antoine', 'video_games'),
    ('Jean-Philippe Puymartin', 'video_games'),
    ('Ubisoft', 'video_games'),
    ('Resident Evil', 'video_games'),
    ('Christopher Lee', 'video_games'),
    ('Faker', 'video_games'),
    ('Clancy Brown', 'video_games'),
    ('Pokémon (série de jeux vidéo)', 'video_games'),
    ('Patrick Préjean', 'video_games'),
    ("Assassin's Creed Black Flag Resynced", 'video_games'),
    ('Inoxtag', 'video_games'),
    ('Michou (vidéaste)', 'video_games'),
    ('Féodor Atkine', 'video_games'),
    ('Grand Theft Auto IV', 'video_games'),
    ('ZA/UM', 'video_games'),
    ("Assassin's Creed IV Black Flag", 'video_games'),
    ('The Legend of Zelda', 'video_games'),
    ('PlayStation 4', 'video_games'),
    ('Manon Azem', 'video_games'),
    ('Jérémie Covillault', 'video_games'),
    ('PlayStation 3', 'video_games'),
    ('Christophe Lemoine', 'video_games'),
    ('Alice David', 'video_games'),
    ('Roger Carel', 'video_games'),
    ('Liste des Pokémon', 'video_games'),
    ('Michelle Rodriguez (actrice)', 'video_games'),
    ('Sam Neill', 'movies'),
    ('Christopher Nolan', 'movies'),
    ('Ester Expósito', 'movies'),
    ('Zendaya', 'movies'),
    ('Tom Holland (acteur)', 'movies'),
    ('Anne Hathaway', 'movies'),
    ('IMAX', 'movies'),
    ("Les Trois Mousquetaires : D'Artagnan", 'movies'),
    ('Matt Damon', 'movies'),
    ('Tomer Sisley', 'movies'),
    ('XXX (film)', 'movies'),
    ('Marc Messier', 'movies'),
    ('Penélope Cruz', 'movies'),
    ('Troie (film)', 'movies'),
    ('Spider-Man: Brand New Day', 'movies'),
    ('Javier Bardem', 'movies'),
    ('Madonna', 'movies'),
    ('Timothée Chalamet', 'movies'),
    ('Les Trois Mousquetaires : Milady', 'movies'),
    ('Inde Navarrette', 'movies'),
    ('Kaylee Hottle', 'movies'),
    ('Simon Abkarian', 'movies'),
    ('Patrick Dewaere', 'movies'),
    ('La mariée était en noir (film)', 'movies'),
    ('Charlize Theron', 'movies'),
    ('Evil Dead Burn', 'movies'),
    ('Eva Green', 'movies'),
    ('Charles Aznavour', 'movies'),
    ('Millie Bobby Brown', 'movies'),
    ('Spider-Man (série de films)', 'movies'),
    ('Le Boucher', 'movies'),
    ('Avengers: Doomsday', 'movies'),
    ("Lupita Nyong'o", 'movies'),
    ('Brad Pitt', 'movies'),
    ('Mortelle Randonnée (film)', 'movies'),
    ('Lyna Khoudri', 'movies'),
    ('Bruce Willis', 'movies'),
    ('Backrooms', 'movies'),
    ('Helena Noguerra', 'movies'),
    ('Benny Safdie', 'movies'),
    ('Catherine Davydzenka', 'movies'),
    ('Univers cinématographique Marvel', 'movies'),
    ('Jean-Marie Bigard', 'movies'),
    ('John Travolta', 'movies'),
    ('Nastassja Kinski', 'movies'),
    ('Johnny Hallyday', 'movies'),
    ('Soudain seuls', 'movies'),
    ('La nuit nous appartient', 'movies'),
    ('Stéphane Audran', 'movies'),
    ('Robert Pattinson', 'movies'),
    ('Tom Cruise', 'movies'),
    ('Terence Hill', 'movies'),
    ('Disclosure Day', 'movies'),
    ('GIGN (mini-série)', 'tv_shows'),
    ('House of the Dragon', 'tv_shows'),
    ('La Petite Maison dans la prairie', 'tv_shows'),
    ('Silo (série télévisée)', 'tv_shows'),
    ('Heroes', 'tv_shows'),
    ('Game of Thrones', 'tv_shows'),
    ('John Leguizamo', 'tv_shows'),
    ('George Clooney', 'tv_shows'),
    ('Camping Paradis', 'tv_shows'),
    ("L'Été 36 (mini-série)", 'tv_shows'),
    ('Tout cela je te le donnerai', 'tv_shows'),
    ('Judith El Zein', 'tv_shows'),
    ("Avatar, le dernier maître de l'air", 'tv_shows'),
    ('Clint Eastwood', 'tv_shows'),
    ('Desperate Housewives', 'tv_shows'),
    ('Liste des épisodes de One Piece', 'tv_shows'),
    ('Jean Dujardin', 'tv_shows'),
    ('Urgences (série télévisée)', 'tv_shows'),
    ('Yellowstone (série télévisée)', 'tv_shows'),
    ('From', 'tv_shows'),
    ('Milly Alcock', 'tv_shows'),
    ('Bud Spencer', 'tv_shows'),
    ('Julia Roberts', 'tv_shows'),
    ('Rihanna', 'tv_shows'),
    ('Alice Pol', 'tv_shows'),
    ('Shannen Doherty', 'tv_shows'),
    ('Rex, chien flic', 'tv_shows'),
    ('Mylène Demongeot', 'tv_shows'),
    ('Everwood', 'tv_shows'),
    ('Les Frères Scott', 'tv_shows'),
    ('O.P.J.', 'tv_shows'),
    ('Armie Hammer', 'tv_shows'),
    ('Catherine Alric', 'tv_shows'),
    ('Liste des épisodes de Camping Paradis', 'tv_shows'),
    ('Le Maître du Zodiaque', 'tv_shows'),
    ('The Walking Dead (série télévisée)', 'tv_shows'),
    ('Volodymyr Zelensky', 'tv_shows'),
    ('Happy Valley (série télévisée)', 'tv_shows'),
    ('Sydney Sweeney', 'tv_shows'),
    ('Jessica Alba', 'tv_shows'),
    ('Alain Delon', 'tv_shows'),
    ('Olivia Rodrigo', 'tv_shows'),
    ('Zoey Deutch', 'tv_shows'),
    ('Saison 14 de Secret Story', 'tv_games'),
    ('Fort Boyard (jeu télévisé)', 'tv_games'),
    ('Cyril Féraud', 'tv_games'),
    ("N'oubliez pas les paroles !", 'tv_games'),
    ('Secret Story', 'tv_games'),
    ('Les Traîtres', 'tv_games'),
    ('Nagui', 'tv_games'),
    ('Les Douze Coups de midi', 'tv_games'),
    ('Saison 13 de Secret Story', 'tv_games'),
    ('Olivier Minne', 'tv_games'),
    ('André Bouchet', 'tv_games'),
    ('Koh-Lanta', 'tv_games'),
    ('Jean-Luc Reichmann', 'tv_games'),
    ('Jean-Pierre Foucault', 'tv_games'),
    ('Laurence Boccolini', 'tv_games'),
    ('Patrice Laffont', 'tv_games'),
    ("Vincent Lagaf'", 'tv_games'),
    ('Saison 13 de Star Academy', 'tv_games'),
    ('Saison 1 de Secret Story', 'tv_games'),
    ('Toy Story 4', 'anime_manga'),
    ('Toy Story 5', 'anime_manga'),
    ('Jim Queen', 'anime_manga'),
    ('Toy Story', 'anime_manga'),
    ('In Waves (film)', 'anime_manga'),
    ('Des Minions et des monstres', 'anime_manga'),
    ('Les Minions', 'anime_manga'),
    ("Les Maîtres de l'univers", 'anime_manga'),
    ("Liste des Classiques d'animation Disney", 'anime_manga'),
    ('Liste des films Pixar', 'anime_manga'),
    ('Studio Ghibli', 'anime_manga'),
    ('Tim Burton', 'anime_manga'),
    ('Musclor', 'anime_manga'),
    ('Les Simpson', 'anime_manga'),
    ('Toy Story 3', 'anime_manga'),
    ('Pixar Animation Studios', 'anime_manga'),
    ('Le Tombeau des lucioles', 'anime_manga'),
    ('Rick et Morty', 'anime_manga'),
    ('Wes Anderson', 'anime_manga'),
    ('Arthur et les Minimoys (film)', 'anime_manga'),
    ('La Légende de Korra', 'anime_manga'),
    ('Walt Disney', 'anime_manga'),
    ('Le Roi lion', 'anime_manga'),
    ('Spider-Man: Across the Spider-Verse', 'anime_manga'),
    ('Toy Story 2', 'anime_manga'),
    ('DreamWorks Animation', 'anime_manga'),
    ('Lucky Luke', 'anime_manga'),
    ('KPop Demon Hunters', 'anime_manga'),
    ('Ratatouille (film)', 'anime_manga'),
    ('Albert Uderzo', 'anime_manga'),
    ("L'Âge de glace (série de films)", 'anime_manga'),
    ('Cars (film)', 'anime_manga'),
    ('Liste des épisodes de Bleach', 'anime_manga'),
    ('Anime', 'anime_manga'),
    ('South Park', 'anime_manga'),
    ('Scooby-Doo', 'anime_manga'),
    ("Bob l'éponge", 'anime_manga'),
    ('Pierre Coffin', 'anime_manga'),
    ('Club Dorothée', 'anime_manga'),
    ('Shrek (film)', 'anime_manga'),
    ('Bleach (manga)', 'anime_manga'),
    ('Liste des épisodes de Naruto', 'anime_manga'),
    ("Arcane (série d'animation)", 'anime_manga'),
    ("L'Odyssée (série télévisée d'animation)", 'anime_manga'),
    ('Moi, moche et méchant', 'anime_manga'),
    ('Totally Spies!', 'anime_manga'),
    ('Jumpers', 'anime_manga'),
    ("Les Douze Travaux d'Astérix", 'anime_manga'),
    ('Skeletor', 'anime_manga'),
    ('Lamine Yamal', 'sports'),
    ('Kylian Mbappé', 'sports'),
    ('Lionel Messi', 'sports'),
    ('Michael Olise', 'sports'),
    ('Coupe du monde de football', 'sports'),
    ('Gianni Infantino', 'sports'),
    ('Erling Haaland', 'sports'),
    ('Zinédine Zidane', 'sports'),
    ('Didier Deschamps', 'sports'),
    ('Cristiano Ronaldo', 'sports'),
    ('Aymeric Laporte', 'sports'),
    ('Équipe de France de football', 'sports'),
    ("Équipe d'Espagne de football", 'sports'),
    ('Tadej Pogačar', 'sports'),
    ('Lucas Digne', 'sports'),
    ('Ousmane Dembélé', 'sports'),
    ('Jude Bellingham', 'sports'),
    ('Rayan Cherki', 'sports'),
    ('Marc Cucurella', 'sports'),
    ('Leandro Paredes', 'sports'),
    ('Paul Seixas', 'sports'),
    ('Yannick Alléno', 'food_cuisine'),
    ('Philippe Etchebest', 'food_cuisine'),
    ('Julie Andrieu', 'food_cuisine'),
    ('Chimichurri', 'food_cuisine'),
    ('Chakchouka', 'food_cuisine'),
    ('Kéfir', 'food_cuisine'),
    ('Kombucha', 'food_cuisine'),
    ('Matcha', 'food_cuisine'),
    ('Cyril Lignac', 'food_cuisine'),
    ('Zaatar', 'food_cuisine'),
    ('Red Bull (entreprise)', 'food_cuisine'),
    ('Halloumi', 'food_cuisine'),
    ('Skyr', 'food_cuisine'),
    ("Association amicale des amateurs d'andouillette authentique", 'food_cuisine'),
    ('Stracciatella (soupe)', 'food_cuisine'),
    ('Poutargue', 'food_cuisine'),
    ('Margarita (cocktail)', 'food_cuisine'),
    ('Tasty Crousty', 'food_cuisine'),
    ('Coca-Cola', 'food_cuisine'),
    ('Jägermeister', 'food_cuisine'),
    ('Picon', 'food_cuisine'),
    ('Thiéboudiène', 'food_cuisine'),
    ('Salmorejo', 'food_cuisine'),
    ('Salade César', 'food_cuisine'),
    ('Salade niçoise', 'food_cuisine'),
    ('Maté', 'food_cuisine'),
    ('Häagen-Dazs', 'food_cuisine'),
    ("McDonald's", 'food_cuisine'),
    ('Poutine (plat)', 'food_cuisine'),
    ('Falafel', 'food_cuisine'),
    ('Cauchemar en cuisine (France)', 'food_cuisine'),
    ('Jean Imbert (cuisinier)', 'food_cuisine'),
    ('Absinthe (spiritueux)', 'food_cuisine'),
    ('Welsh (plat)', 'food_cuisine'),
    ('Angostura (boisson)', 'food_cuisine'),
    ('Alain Ducasse', 'food_cuisine'),
    ('Anne-Sophie Pic', 'food_cuisine'),
    ('Fricadelle', 'food_cuisine'),
    ('Gin', 'food_cuisine'),
    ('Andouillette', 'food_cuisine'),
    ('Orangina', 'food_cuisine'),
    ('Unilever', 'food_cuisine'),
    ('Magnum (marque)', 'food_cuisine'),
    ('Spiruline alimentaire', 'food_cuisine'),
    ('Tofu', 'food_cuisine'),
    ('Norbert Tarayre', 'food_cuisine'),
    ('Gombo', 'food_cuisine'),
    ('Anthony Bourdain', 'food_cuisine'),
    ('Kimchi', 'food_cuisine'),
    ('Paprika', 'food_cuisine'),
    ('Danone', 'food_cuisine'),
    ('Cognac (eau-de-vie)', 'food_cuisine'),
    ('Maigre (poisson)', 'food_cuisine'),
    ('Carbonade flamande', 'food_cuisine'),
    ('Focaccia', 'food_cuisine'),
    ('Quick (restauration)', 'food_cuisine'),
    ('Cachaça', 'food_cuisine'),
    ('Dame blanche (dessert)', 'food_cuisine'),
    ('Paul Bocuse', 'food_cuisine'),
    ('Le Menu', 'food_cuisine'),
    ('Negroni (cocktail)', 'food_cuisine'),
    ('Morue', 'food_cuisine'),
    ("Liste des pays par taux d'obésité", 'food_cuisine'),
    ('Yuzu', 'food_cuisine'),
    ('Pomme de terre', 'food_cuisine'),
    ('Kouign-amann', 'food_cuisine'),
    ('Tomate', 'food_cuisine'),
    ('Caïpirinha', 'food_cuisine'),
    ('Feta', 'food_cuisine'),
    ('Schweppes', 'food_cuisine'),
    ('Red Bull', 'food_cuisine'),
    ('Ceviche', 'food_cuisine'),
    ('Pitaya', 'food_cuisine'),
    ('Achillée millefeuille', 'food_cuisine'),
    ('Curaçao (liqueur)', 'food_cuisine'),
    ('Chouchen', 'food_cuisine'),
    ('Bicarbonate de sodium', 'food_cuisine'),
    ('Kopi luwak', 'food_cuisine'),
    ('Caponata', 'food_cuisine'),
    ('Auguste Escoffier', 'food_cuisine'),
    ('Gordon Ramsay', 'food_cuisine'),
    ('Miko (marque)', 'food_cuisine'),
    ('Vitello tonnato', 'food_cuisine'),
    ('Liste de légumes', 'food_cuisine'),
    ('Vodka', 'food_cuisine'),
    ('Pâtes à la carbonara', 'food_cuisine'),
    ('Bernard Loiseau', 'food_cuisine'),
    ('Mondelez International', 'food_cuisine'),
    ('Maïs', 'food_cuisine'),
    ('Arancini', 'food_cuisine'),
    ('François Vatel', 'food_cuisine'),
    ('Limoncello', 'food_cuisine'),
    ('Maïté', 'food_cuisine'),
    ('Tarte tropézienne', 'food_cuisine'),
    ('Affogato', 'food_cuisine'),
    ('Yassa (plat)', 'food_cuisine'),
    ('Eau', 'food_cuisine'),
    ('Aligot', 'food_cuisine'),
    ('Lactalis', 'food_cuisine'),
    ('Sauce gribiche', 'food_cuisine'),
    ('Rakı', 'food_cuisine'),
    ('Brugnon', 'food_cuisine'),
    ('Piperade', 'food_cuisine'),
    ('Tiramisu', 'food_cuisine'),
    ('Bouillabaisse', 'food_cuisine'),
    ('Œuf Benedict', 'food_cuisine'),
    ('Œuf de cent ans', 'food_cuisine'),
    ('Get 27', 'food_cuisine'),
    ('Vermouth', 'food_cuisine'),
    ('Juan Arbeláez', 'food_cuisine'),
    ('Tzatzíki', 'food_cuisine'),
    ('Taboulé', 'food_cuisine'),
    ('Tielle', 'food_cuisine'),
    ('Charles de Gaulle', 'history'),
    ('Napoléon Ier', 'history'),
    ('Louis XIV', 'history'),
    ('Maria Carolina de Bourbon des Deux-Siciles', 'history'),
    ('Philippe Pétain', 'history'),
    ("Jeanne d'Arc", 'history'),
    ('Franklin Delano Roosevelt', 'history'),
    ('Adolf Hitler', 'history'),
    ('Seconde Guerre mondiale', 'history'),
    ('Louis XV', 'history'),
    ('Toulouse', 'history'),
    ('Napoléon III', 'history'),
    ('Première Guerre mondiale', 'history'),
    ('Prise de la Bastille', 'history'),
    ('Louis XVI', 'history'),
    ('Shoah', 'history'),
    ("Guerre d'indépendance des États-Unis", 'history'),
    ('Catherine de Médicis', 'history'),
    ('Liste des monarques de France', 'history'),
    ('Jules César', 'history'),
    ('Marc Bloch', 'history'),
    ("Marie-Antoinette d'Autriche", 'history'),
    ('Gilbert du Motier de La Fayette', 'history'),
    ('Révolution française', 'history'),
    ('Catherine II', 'history'),
    ('Union européenne', 'history'),
    ('Charles Quint', 'history'),
    ('Maximilien de Robespierre', 'history'),
    ('Affaire Dreyfus', 'history'),
    ('Ibrahim Traoré', 'history'),
    ('Richard Cœur de Lion', 'history'),
    ('Empire ottoman', 'history'),
    ('Maison Plantagenêt', 'history'),
    ('Régime de Vichy', 'history'),
    ('Charles-Maurice de Talleyrand-Périgord', 'history'),
    ('Joséphine de Beauharnais', 'history'),
    ("Invasion de l'Ukraine par la Russie", 'history'),
    ('Royaume de France', 'history'),
    ('Philippe II Auguste', 'history'),
    ('François-Joseph Ier', 'history'),
    ('Saint-Empire romain germanique', 'history'),
    ('Nicolae Ceaușescu', 'history'),
    ('Jean Jaurès', 'history'),
    ('Commune de Paris', 'history'),
    ('Napoléon II', 'history'),
    ('Marc Aurèle', 'history'),
    ('La casa de papel', 'history'),
    ("Liste des monarques d'Angleterre", 'history'),
    ('Jean-Bedel Bokassa', 'history'),
    ('Germaine de Staël', 'history'),
    ('Génocide des Tutsi du Rwanda', 'history'),
    ('Grèce antique', 'history'),
    ('Fête de la Fédération', 'history'),
    ('Organisation des Nations unies', 'history'),
    ('Thomas Sankara', 'history'),
    ("Déclaration d'indépendance des États-Unis", 'history'),
    ("Organisation du traité de l'Atlantique nord", 'history'),
    ('Île de Noirmoutier', 'history'),
    ('Génocide de Srebrenica', 'history'),
    ('Auschwitz', 'history'),
    ('Mahomet', 'history'),
    ('Fernand de Magellan', 'history'),
    ('Babylone', 'history'),
    ('Massacre de la Saint-Barthélemy', 'history'),
    ('Département français', 'geography'),
    ('Gironde (département)', 'geography'),
    ('Liste des capitales du monde', 'geography'),
    ('Liste des pays du monde', 'geography'),
    ('Île Maurice', 'geography'),
    ('Mont Rushmore', 'geography'),
    ('Var (département)', 'geography'),
    ('Liste des pays par population', 'geography'),
    ('Corse', 'geography'),
    ('Melilla', 'geography'),
    ('La Réunion', 'geography'),
    ('États des États-Unis', 'geography'),
    ('Christophe Colomb', 'geography'),
    ('Région française', 'geography'),
    ('Québec', 'geography'),
    ('Ardèche (département)', 'geography'),
    ('Guadeloupe', 'geography'),
    ('Landes (département)', 'geography'),
    ('Waze', 'geography'),
    ('Gibraltar', 'geography'),
    ('Triangle des Bermudes', 'geography'),
    ('Danube', 'geography'),
    ('Europe', 'geography'),
    ('Nouvelle-Calédonie', 'geography'),
    ('Vendée (département)', 'geography'),
    ('Drôme (département)', 'geography'),
    ('Sahara occidental', 'geography'),
    ('Guyane', 'geography'),
    ('Îles Canaries', 'geography'),
    ('Creuse (département)', 'geography'),
    ('Polynésie française', 'geography'),
    ('Taïwan', 'geography'),
    ('Martinique', 'geography'),
    ('Espace Schengen', 'geography'),
    ('Mont Ventoux', 'geography'),
    ('Aveyron (département)', 'geography'),
    ('Mer Méditerranée', 'geography'),
    ('Cantal (département)', 'geography'),
    ('Seine-et-Marne', 'geography'),
    ("France d'outre-mer", 'geography'),
    ('Plateau de Millevaches', 'geography'),
    ("Provence-Alpes-Côte d'Azur", 'geography'),
    ('Mayotte', 'geography'),
    ('Afrique', 'geography'),
    ('Vosges (département)', 'geography'),
    ('Everest', 'geography'),
    ('Quercy', 'geography'),
    ('Cookie (informatique)', 'technology'),
    ('ChatGPT', 'technology'),
    ('Google', 'technology'),
    ('WhatsApp', 'technology'),
    ('Gmail', 'technology'),
    ('Wiki', 'technology'),
    ('Steve Jobs', 'technology'),
    ('Google Chrome', 'technology'),
    ('World Wide Web', 'technology'),
    ('C (langage)', 'technology'),
    ('Dark web', 'technology'),
    ('Céline Dept', 'technology'),
    ('Code QR', 'technology'),
    ('Microsoft Outlook', 'technology'),
    ('Google Maps', 'technology'),
    ('Théodort', 'technology'),
    ('Arthur Mensch', 'technology'),
    ('IPhone', 'technology'),
    ('Telegram (application)', 'technology'),
    ('Bill Gates', 'technology'),
    ('Mark Zuckerberg', 'technology'),
    ('Internet', 'technology'),
    ('Alan Turing', 'technology'),
    ('Pavel Dourov', 'technology'),
    ('R (langage)', 'technology'),
    ('Canva', 'technology'),
    ('Ada Lovelace', 'technology'),
    ('Google Play', 'technology'),
    ('Apple', 'technology'),
    ('Dario Amodei', 'technology'),
    ('Google Traduction', 'technology'),
    ('Laurent Alexandre', 'technology'),
    ('Liste des codes HTTP', 'technology'),
    ('Swan & Néo', 'technology'),
    ('Yann Le Cun', 'technology'),
    ('Combinaisons de touche Alt', 'technology'),
    ('Capgemini', 'technology'),
    ('Linux', 'technology'),
    ('Microsoft', 'technology'),
    ('Spotify', 'technology'),
    ('MacOS', 'technology'),
    ('Android', 'technology'),
    ('Signal (application)', 'technology'),
    ('Outlook.com', 'technology'),
    ('BarCamp', 'technology'),
    ('Hugging Face', 'technology'),
    ('Google (moteur de recherche)', 'technology'),
    ('Null', 'technology'),
    ('Interstellar', 'science_space'),
    ('Marie Curie', 'science_space'),
    ('Albert Einstein', 'science_space'),
    ("Liste d'éclipses solaires", 'science_space'),
    ('Nikola Tesla', 'science_space'),
    ('Apollo 11', 'science_space'),
    ('Robert Oppenheimer', 'science_space'),
    ('Éclipse solaire', 'science_space'),
    ('Claudia Sheinbaum', 'science_space'),
    ('Système solaire', 'science_space'),
    ('Stephen Hawking', 'science_space'),
    ('Étienne Klein', 'science_space'),
    ('Terre', 'science_space'),
    ('Hectare', 'science_space'),
    ('Chat de Schrödinger', 'science_space'),
    ('Fata morgana (optique)', 'science_space'),
    ('Cumulonimbus', 'science_space'),
    ('Benjamin Franklin', 'science_space'),
    ('Galilée (savant)', 'science_space'),
    ('Soleil', 'science_space'),
    ("Machine d'Anticythère", 'science_space'),
    ('Lune', 'science_space'),
    ('Vénus (planète)', 'science_space'),
    ('Aristote', 'science_space'),
    ("Moment d'une force", 'science_space'),
    ('Blaise Pascal', 'science_space'),
    ('René Descartes', 'science_space'),
    ('Voie lactée', 'science_space'),
    ('Point de rosée', 'science_space'),
    ('Isaac Newton', 'science_space'),
    ('Programme Apollo', 'science_space'),
    ('Eau lourde', 'science_space'),
    ('Paradoxe de Fermi', 'science_space'),
    ('Hélium', 'science_space'),
    ('Trou noir', 'science_space'),
    ('Irène Joliot-Curie', 'science_space'),
    ('Brian May', 'science_space'),
    ('Thomas Edison', 'science_space'),
    ('Cratère de Chicxulub', 'science_space'),
    ('Grande Ourse', 'science_space'),
    ('Entropie (thermodynamique)', 'science_space'),
    ('Pluton (planète naine)', 'science_space'),
    ('Pic du Midi de Bigorre', 'science_space'),
    ('Jupiter (planète)', 'science_space'),
    ('ITER', 'science_space'),
    ('Big Bang', 'science_space'),
    ('Lazare Carnot', 'science_space'),
    ('Odyssée', 'art_literature'),
    ('Sophie Brocas', 'art_literature'),
    ('Iliade', 'art_literature'),
    ('Hélène (mythologie)', 'art_literature'),
    ('Françoise Mallet-Joris', 'art_literature'),
    ('Homère', 'art_literature'),
    ('La Servante écarlate', 'art_literature'),
    ('Laura Ingalls Wilder', 'art_literature'),
    ('Les Trois Mousquetaires', 'art_literature'),
    ('Alexandre Dumas', 'art_literature'),
    ('The Backrooms', 'art_literature'),
    ('Victor Hugo', 'art_literature'),
    ('George Sand', 'art_literature'),
    ('Romain Gary', 'art_literature'),
    ('Le Comte de Monte-Cristo', 'art_literature'),
    ('Sylvain Tesson', 'art_literature'),
    ('Albert Camus', 'art_literature'),
    ('Harlan Coben', 'art_literature'),
    ('Freida McFadden', 'art_literature'),
    ('Gabriel Matzneff', 'art_literature'),
    ('Amélie Nothomb', 'art_literature'),
    ('Roi Arthur', 'art_literature'),
    ('Émile Zola', 'art_literature'),
    ('Jules Verne', 'art_literature'),
    ('Harry Potter', 'art_literature'),
    ('Stephen King', 'art_literature'),
    ('Marlène Jobert', 'art_literature'),
    ('Georges Pompidou', 'art_literature'),
    ('Marcel Pagnol', 'art_literature'),
    ('Pierre Lemaitre', 'art_literature'),
    ('Maxime Chattam', 'art_literature'),
    ('Arthur Rimbaud', 'art_literature'),
    ('Fred Vargas', 'art_literature'),
    ('Alain Soral', 'art_literature'),
    ('Gaël Faye', 'art_literature'),
    ('Honoré de Balzac', 'art_literature'),
    ('Colette', 'art_literature'),
    ('Louis-Ferdinand Céline', 'art_literature'),
    ('Rachel Khan', 'art_literature'),
    ('Antoine de Saint-Exupéry', 'art_literature'),
    ("L'Étranger", 'art_literature'),
    ('Franck Thilliez', 'art_literature'),
    ('André Malraux', 'art_literature'),
    ('Molière', 'art_literature'),
    ('Le Rouge et le Noir', 'art_literature'),
    ('Fiodor Dostoïevski', 'art_literature'),
    ('Personnages du Trône de fer', 'art_literature'),
    ('Agatha Christie', 'art_literature'),
    ('Les Misérables', 'art_literature'),
    ('Jean-Jacques Rousseau', 'art_literature'),
    ('Charles Consigny', 'art_literature'),
    ('Ulysse', 'mythology_folklore'),
    ('Guerre de Troie', 'mythology_folklore'),
    ('Agamemnon', 'mythology_folklore'),
    ('Calypso', 'mythology_folklore'),
    ('Circé', 'mythology_folklore'),
    ('Lestrygons', 'mythology_folklore'),
    ('Troie', 'mythology_folklore'),
    ('Achille', 'mythology_folklore'),
    ('Télémaque', 'mythology_folklore'),
    ('Sinon', 'mythology_folklore'),
    ('Ménélas', 'mythology_folklore'),
    ('Clytemnestre', 'mythology_folklore'),
    ('Cheval de Troie', 'mythology_folklore'),
    ('Nausicaa', 'mythology_folklore'),
    ('Polyphème', 'mythology_folklore'),
    ('Kavinsky', 'music'),
    ('Bonnie Tyler', 'music'),
    ('Shakira', 'music'),
    ('Barbara Butch', 'music'),
    ('YouTube', 'music'),
    ('Marie-Paule Belle', 'music'),
    ('Michael Jackson', 'music'),
    ('Bad Bunny', 'music'),
    ('BTS (groupe)', 'music'),
    ('Lauren Bennett', 'music'),
    ('The Weeknd', 'music'),
    ('Bee Gees', 'music'),
    ("Shy'm", 'music'),
    ('Serge Lama', 'music'),
    ('Katy Perry', 'music'),
    ('Laurent Voulzy', 'music'),
    ('Guesch Patti', 'music'),
    ('XXL (chanson)', 'music'),
    ('System of a Down', 'music'),
    ('La Marseillaise', 'music'),
    ('ABBA', 'music'),
    ('Jean-Jacques Goldman', 'music'),
    ('Hugues Aufray', 'music'),
    ('Mosimann', 'music'),
    ('Taylor Swift', 'music'),
    ('Michel Sardou', 'music'),
    ('Alain Souchon', 'music'),
    ('Eva (chanteuse française)', 'music'),
    ('Dalida', 'music'),
    ('Gims', 'music'),
    ('Vanessa Paradis', 'music'),
    ('Justin Bieber', 'music'),
    ('Isabelle Adjani', 'music'),
    ('Amy Winehouse', 'music'),
    ('Theodora (chanteuse)', 'music'),
    ('Aya Nakamura', 'music'),
    ('Jérémy Frerot', 'music'),
    ('Gaëtan Roussel', 'music'),
    ('Freddie Mercury', 'music'),
    ('Alain Barrière', 'music'),
    ('Renaud', 'music'),
    ('Julien Clerc', 'music'),
    ('Jul (rappeur)', 'music'),
    ('La Fièvre du samedi soir', 'music'),
    ('Édith Piaf', 'music'),
    ('The Rolling Stones', 'music'),
    ('Jennifer Lopez', 'music'),
    ('Dua Lipa', 'music'),
    ('Philippe Katerine', 'music'),
    ('Barry Gibb', 'music'),
    ('Miki (artiste)', 'music'),
    ('Joe Dassin', 'music'),
    ('The Cure', 'music'),
    ('Cécile Cassel', 'music'),
    ('Charlotte Cardin', 'music'),
    ('Adèle Castillon', 'music'),
    ('Catherine Ringer', 'music'),
    ('Line Renaud', 'music'),
    ('Bertrand Cantat', 'music'),
    ('Quentin Dupieux', 'music'),
]
