"""Curated Wikipelago article pool: (Wikipedia title, category)."""

ENTERTAINMENT_ARTICLE_POOL: list[tuple[str, str]] = [
    ('Minecraft', 'video_games'),
    ('Fortnite', 'video_games'),
    ('Roblox', 'video_games'),
    ('League of Legends', 'video_games'),
    ('Dota 2', 'video_games'),
    ('Valorant', 'video_games'),
    ('Overwatch', 'video_games'),
    ('Counter-Strike', 'video_games'),
    ('Apex Legends', 'video_games'),
    ('Rocket League', 'video_games'),
    ('Grand Theft Auto V', 'video_games'),
    ('The Elder Scrolls V: Skyrim', 'video_games'),
    ('The Witcher 3: Wild Hunt', 'video_games'),
    ('Dark Souls', 'video_games'),
    ('Elden Ring', 'video_games'),
    ('Sekiro: Shadows Die Twice', 'video_games'),
    ('Bloodborne', 'video_games'),
    ('Hades (video game)', 'video_games'),
    ('Stardew Valley', 'video_games'),
    ('Terraria', 'video_games'),
    ('Celeste (video game)', 'video_games'),
    ('Hollow Knight', 'video_games'),
    ('Undertale', 'video_games'),
    ('Cuphead', 'video_games'),
    ('Dead Cells', 'video_games'),
    ('Slay the Spire', 'video_games'),
    ('Balatro', 'video_games'),
    ('Portal (video game)', 'video_games'),
    ('Portal 2', 'video_games'),
    ('Half-Life 2', 'video_games'),
    ('Left 4 Dead 2', 'video_games'),
    ('Team Fortress 2', 'video_games'),
    ('BioShock', 'video_games'),
    ('Mass Effect 2', 'video_games'),
    ('Red Dead Redemption 2', 'video_games'),
    ('God of War (2018 video game)', 'video_games'),
    ('The Last of Us', 'video_games'),
    ('The Last of Us Part II', 'video_games'),
    ("Uncharted 4: A Thief's End", 'video_games'),
    ('Ghost of Tsushima', 'video_games'),
    ('Horizon Zero Dawn', 'video_games'),
    ("Marvel's Spider-Man", 'video_games'),
    ('Super Mario Bros.', 'video_games'),
    ('Super Mario 64', 'video_games'),
    ('Super Mario Odyssey', 'video_games'),
    ('Mario Kart 8', 'video_games'),
    ('The Legend of Zelda', 'video_games'),
    ('The Legend of Zelda: Ocarina of Time', 'video_games'),
    ('The Legend of Zelda: Breath of the Wild', 'video_games'),
    ('The Legend of Zelda: Tears of the Kingdom', 'video_games'),
    ('Pokémon Red, Blue, and Yellow', 'video_games'),
    ('Pokémon Gold and Silver', 'video_games'),
    ('Pokémon Scarlet and Violet', 'video_games'),
    ('Metroid Prime', 'video_games'),
    ('Animal Crossing: New Horizons', 'video_games'),
    ('Splatoon 3', 'video_games'),
    ('Super Smash Bros. Ultimate', 'video_games'),
    ('Tetris', 'video_games'),
    ('Pac-Man', 'video_games'),
    ('Space Invaders', 'video_games'),
    ('Street Fighter II', 'video_games'),
    ('Mortal Kombat', 'video_games'),
    ('Tekken 7', 'video_games'),
    ('Final Fantasy VII', 'video_games'),
    ('Final Fantasy XIV', 'video_games'),
    ('Persona 5', 'video_games'),
    ('Kingdom Hearts', 'video_games'),
    ('Nier: Automata', 'video_games'),
    ('Metal Gear Solid 3: Snake Eater', 'video_games'),
    ('Resident Evil 4', 'video_games'),
    ('Silent Hill 2', 'video_games'),
    ('Halo: Combat Evolved', 'video_games'),
    ('Halo 3', 'video_games'),
    ('Call of Duty 4: Modern Warfare', 'video_games'),
    ('Call of Duty: Warzone (2020 video game)', 'video_games'),
    ('Battlefield 1', 'video_games'),
    ('Doom (1993 video game)', 'video_games'),
    ('Doom Eternal', 'video_games'),
    ('Quake (video game)', 'video_games'),
    ('Destiny 2', 'video_games'),
    ('Warframe', 'video_games'),
    ('Among Us', 'video_games'),
    ('Fall Guys', 'video_games'),
    ('Genshin Impact', 'video_games'),
    ('World of Warcraft', 'video_games'),
    ('RuneScape', 'video_games'),
    ('Diablo II', 'video_games'),
    ('Diablo IV', 'video_games'),
    ('StarCraft', 'video_games'),
    ('StarCraft II: Wings of Liberty', 'video_games'),
    ('Age of Empires II', 'video_games'),
    ('Civilization VI', 'video_games'),
    ('The Sims 4', 'video_games'),
    ('Cities: Skylines', 'video_games'),
    ('XCOM 2', 'video_games'),
    ('FIFA 23', 'sports'),
    ('EA Sports FC 24', 'video_games'),
    ('NBA 2K24', 'sports'),
    ('Madden NFL 24', 'sports'),
    ('Gran Turismo 7', 'video_games'),
    ('Forza Horizon 5', 'video_games'),
    ('Need for Speed', 'video_games'),
    ("Assassin's Creed II", 'video_games'),
    ("Assassin's Creed Valhalla", 'video_games'),
    ('Cyberpunk 2077', 'video_games'),
    ("Baldur's Gate 3", 'video_games'),
    ('Disco Elysium', 'video_games'),
    ('Outer Wilds', 'video_games'),
    ("No Man's Sky", 'video_games'),
    ('Subnautica', 'video_games'),
    ('Sea of Thieves', 'video_games'),
    ('Phasmophobia (video game)', 'video_games'),
    ('Lethal Company', 'video_games'),
    ('Clash of Clans', 'video_games'),
    ('Candy Crush Saga', 'video_games'),
    ('Pokémon Go', 'video_games'),
    ('Angry Birds', 'video_games'),
    ('Chess', 'board_games'),
    ('Checkers', 'board_games'),
    ('Go (game)', 'board_games'),
    ('Backgammon', 'board_games'),
    ('Scrabble', 'board_games'),
    ('Monopoly (game)', 'board_games'),
    ('Risk (game)', 'board_games'),
    ('Cluedo', 'board_games'),
    ('The Game of Life', 'board_games'),
    ('Battleship (game)', 'board_games'),
    ('Connect Four', 'board_games'),
    ('Jenga', 'board_games'),
    ('Twister (game)', 'board_games'),
    ('Uno (card game)', 'board_games'),
    ('Poker', 'board_games'),
    ('Mahjong', 'board_games'),
    ('Catan', 'board_games'),
    ('Ticket to Ride (board game)', 'board_games'),
    ('Carcassonne (board game)', 'board_games'),
    ('Pandemic (board game)', 'board_games'),
    ('7 Wonders (board game)', 'board_games'),
    ('Dominion (card game)', 'board_games'),
    ('Terraforming Mars (board game)', 'board_games'),
    ('Wingspan (board game)', 'board_games'),
    ('Azul (board game)', 'board_games'),
    ('Gloomhaven', 'board_games'),
    ('Root (board game)', 'board_games'),
    ('Codenames (board game)', 'board_games'),
    ('Exploding Kittens', 'board_games'),
    ('Magic: The Gathering', 'board_games'),
    ('Yu-Gi-Oh!', 'board_games'),
    ('Pokémon Trading Card Game', 'board_games'),
    ('Dungeons & Dragons', 'board_games'),
    ('Warhammer 40,000', 'board_games'),
    ('Jaws (film)', 'movies'),
    ('Star Wars (film)', 'movies'),
    ('The Empire Strikes Back', 'movies'),
    ('Return of the Jedi', 'movies'),
    ('The Lord of the Rings: The Fellowship of the Ring', 'movies'),
    ('The Lord of the Rings: The Two Towers', 'movies'),
    ('The Lord of the Rings: The Return of the King', 'movies'),
    ("Harry Potter and the Philosopher's Stone (film)", 'movies'),
    ('The Godfather', 'movies'),
    ('The Dark Knight', 'movies'),
    ('The Shawshank Redemption', 'movies'),
    ('Pulp Fiction', 'movies'),
    ('Forrest Gump', 'movies'),
    ('Fight Club', 'movies'),
    ('Inception', 'movies'),
    ('Interstellar (film)', 'movies'),
    ('The Matrix', 'movies'),
    ('Gladiator (2000 film)', 'movies'),
    ('Titanic (1997 film)', 'movies'),
    ('Avatar (2009 film)', 'movies'),
    ('Avatar: The Way of Water', 'movies'),
    ('Top Gun: Maverick', 'movies'),
    ('Jurassic Park', 'movies'),
    ('Back to the Future', 'movies'),
    ('Ghostbusters', 'movies'),
    ('Home Alone', 'movies'),
    ('E.T. the Extra-Terrestrial', 'movies'),
    ('The Lion King', 'movies'),
    ('Toy Story', 'movies'),
    ('Toy Story 3', 'movies'),
    ('Finding Nemo', 'movies'),
    ('The Incredibles', 'movies'),
    ('Inside Out', 'movies'),
    ('Coco (2017 film)', 'movies'),
    ('Shrek', 'movies'),
    ('Frozen (2013 film)', 'movies'),
    ('Moana (2016 film)', 'movies'),
    ('Spider-Man: Into the Spider-Verse', 'movies'),
    ('Spider-Man: Across the Spider-Verse', 'movies'),
    ('Iron Man (2008 film)', 'movies'),
    ('The Avengers (2012 film)', 'movies'),
    ('Avengers: Infinity War', 'movies'),
    ('Avengers: Endgame', 'movies'),
    ('Guardians of the Galaxy (film)', 'movies'),
    ('Black Panther (film)', 'movies'),
    ('The Super Mario Bros. Movie', 'video_games'),
    ('Mad Max: Fury Road', 'movies'),
    ('Whiplash (2014 film)', 'movies'),
    ('La La Land', 'movies'),
    ('The Social Network', 'movies'),
    ('Oppenheimer (film)', 'movies'),
    ('Barbie (film)', 'movies'),
    ('Dune (2021 film)', 'movies'),
    ('Dune: Part Two', 'movies'),
    ('The Simpsons', 'tv_shows'),
    ('Family Guy', 'tv_shows'),
    ('South Park', 'tv_shows'),
    ('SpongeBob SquarePants', 'tv_shows'),
    ('Avatar: The Last Airbender', 'tv_shows'),
    ('The Legend of Korra', 'tv_shows'),
    ('Rick and Morty', 'tv_shows'),
    ('Adventure Time', 'tv_shows'),
    ('Regular Show', 'tv_shows'),
    ('Gravity Falls', 'tv_shows'),
    ('Arcane (TV series)', 'tv_shows'),
    ('Bluey (TV series)', 'tv_shows'),
    ('Game of Thrones', 'tv_shows'),
    ('House of the Dragon', 'tv_shows'),
    ('Breaking Bad', 'tv_shows'),
    ('Better Call Saul', 'tv_shows'),
    ('The Sopranos', 'tv_shows'),
    ('The Wire', 'tv_shows'),
    ('Friends', 'tv_shows'),
    ('Seinfeld', 'tv_shows'),
    ('The Office (American TV series)', 'tv_shows'),
    ('Parks and Recreation', 'tv_shows'),
    ('Brooklyn Nine-Nine', 'tv_shows'),
    ('How I Met Your Mother', 'tv_shows'),
    ('The Big Bang Theory', 'tv_shows'),
    ('Modern Family', 'tv_shows'),
    ('Ted Lasso', 'tv_shows'),
    ('Stranger Things', 'tv_shows'),
    ('Wednesday (TV series)', 'tv_shows'),
    ('The Walking Dead (TV series)', 'tv_shows'),
    ('Lost (TV series)', 'tv_shows'),
    ('The Last of Us (TV series)', 'tv_shows'),
    ('The Mandalorian', 'tv_shows'),
    ('Andor', 'tv_shows'),
    ('Loki (TV series)', 'tv_shows'),
    ('WandaVision', 'tv_shows'),
    ('Daredevil (TV series)', 'tv_shows'),
    ('Sherlock (TV series)', 'tv_shows'),
    ('Doctor Who', 'tv_shows'),
    ('Black Mirror', 'tv_shows'),
    ('The Boys (TV series)', 'tv_shows'),
    ('Invincible (TV series)', 'tv_shows'),
    ('Peaky Blinders (TV series)', 'tv_shows'),
    ('Narcos', 'tv_shows'),
    ('True Detective', 'tv_shows'),
    ('Dexter (TV series)', 'tv_shows'),
    ('House (TV series)', 'tv_shows'),
    ("Grey's Anatomy", 'tv_shows'),
    ('The Crown (TV series)', 'tv_shows'),
    ('Chernobyl (miniseries)', 'tv_shows'),
    ("The Queen's Gambit (miniseries)", 'tv_shows'),
    ('The Bear (TV series)', 'tv_shows'),
    ('Succession (TV series)', 'tv_shows'),
    ('Euphoria (American TV series)', 'tv_shows'),
    ('Cobra Kai', 'tv_shows'),
    ('Squid Game', 'tv_shows'),
    ('One Piece (2023 TV series)', 'tv_shows'),
    ('The Witcher (TV series)', 'tv_shows'),
    ('The Umbrella Academy (TV series)', 'tv_shows'),
    ('Prison Break', 'tv_shows'),
    ('Vikings (TV series)', 'tv_shows'),
    ('Naruto', 'anime_manga'),
    ('One Piece', 'anime_manga'),
    ('Dragon Ball', 'anime_manga'),
    ('Attack on Titan', 'anime_manga'),
    ('Death Note', 'anime_manga'),
    ('Demon Slayer: Kimetsu no Yaiba', 'anime_manga'),
    ('Jujutsu Kaisen', 'anime_manga'),
    ('My Hero Academia', 'anime_manga'),
    ('Fullmetal Alchemist', 'anime_manga'),
    ('Bleach (TV series)', 'tv_shows'),
    ('Tokyo Ghoul', 'anime_manga'),
    ('Cowboy Bebop', 'anime_manga'),
    ('Neon Genesis Evangelion', 'anime_manga'),
    ('Hunter × Hunter', 'anime_manga'),
    ('Sailor Moon', 'anime_manga'),
    ('World cup', 'sports'),
    ('UEFA Champions League', 'sports'),
    ('Premier League', 'sports'),
    ('National Basketball Association', 'sports'),
    ('National Football League', 'sports'),
    ('Major League Baseball', 'sports'),
    ('Olympic Games', 'sports'),
    ('Summer Olympic Games', 'sports'),
    ('Winter Olympic Games', 'sports'),
    ('FIFA World Cup', 'sports'),
    ('Wimbledon Championships', 'sports'),
    ('Super Bowl', 'sports'),
    ('Formula One', 'sports'),
    ('Tour de France', 'sports'),
    ('Cricket World Cup', 'sports'),
    ('American football', 'sports'),
    ('Basketball', 'sports'),
    ('Baseball', 'sports'),
    ('Tennis', 'sports'),
    ('Association football', 'sports'),
    ('Milky Way', 'science_space'),
    ('Solar System', 'science_space'),
    ('Earth', 'science_space'),
    ('Mars', 'science_space'),
    ('Jupiter', 'science_space'),
    ('Saturn', 'science_space'),
    ('Moon', 'science_space'),
    ('Black hole', 'science_space'),
    ('Galaxy', 'science_space'),
    ('Astronomy', 'science_space'),
    ('Space exploration', 'science_space'),
    ('Apollo 11', 'science_space'),
    ('International Space Station', 'science_space'),
    ('Hubble Space Telescope', 'science_space'),
    ('James Webb Space Telescope', 'science_space'),
    ('Physics', 'science_space'),
    ('Biology', 'science_space'),
    ('Mathematics', 'science_space'),
    ('Google', 'technology'),
    ('YouTube', 'technology'),
    ('Wikipedia', 'technology'),
    ('Internet', 'technology'),
    ('World Wide Web', 'technology'),
    ('Web browser', 'technology'),
    ('Firefox', 'technology'),
    ('Google Chrome', 'technology'),
    ('Microsoft Edge', 'technology'),
    ('OpenAI', 'technology'),
    ('Artificial intelligence', 'technology'),
    ('Virtual reality', 'technology'),
    ('Smartphone', 'technology'),
    ('iPhone', 'technology'),
    ('Android (operating system)', 'technology'),
    ('PlayStation', 'video_games'),
    ('Xbox', 'video_games'),
    ('Nintendo', 'video_games'),
    ('Steam (service)', 'technology'),
    ('Ancient Egypt', 'history'),
    ('Ancient Greece', 'history'),
    ('Roman Empire', 'history'),
    ('Middle Ages', 'history'),
    ('Renaissance', 'history'),
    ('Industrial Revolution', 'history'),
    ('World War I', 'history'),
    ('World War II', 'history'),
    ('Cold War', 'history'),
    ('Silk Road', 'history'),
    ('Black Death', 'history'),
    ('Moon landing', 'history'),
    ('History of writing', 'history'),
    ('History of the Internet', 'technology'),
    ('Great Wall of China', 'history'),
    ('Machu Picchu', 'history'),
    ('Eiffel Tower', 'geography'),
    ('Colosseum', 'history'),
    ('Statue of Liberty', 'history'),
    ('Taj Mahal', 'geography'),
    ('Mount Everest', 'geography'),
    ('Amazon rainforest', 'geography'),
    ('Sahara', 'geography'),
    ('Pacific Ocean', 'geography'),
    ('Atlantic Ocean', 'geography'),
    ('Nile', 'geography'),
    ('Tokyo', 'geography'),
    ('New York City', 'geography'),
    ('Paris', 'geography'),
    ('London', 'geography'),
    ('Pizza', 'food_cuisine'),
    ('Sushi', 'food_cuisine'),
    ('Hamburger', 'food_cuisine'),
    ('Taco', 'food_cuisine'),
    ('Pasta', 'food_cuisine'),
    ('Ramen', 'food_cuisine'),
    ('Chocolate', 'food_cuisine'),
    ('Coffee', 'food_cuisine'),
    ('Tea', 'food_cuisine'),
    ('Ice cream', 'food_cuisine'),
    ('Sandwich', 'food_cuisine'),
    ('French cuisine', 'food_cuisine'),
    ('Italian cuisine', 'food_cuisine'),
    ('Japanese cuisine', 'food_cuisine'),
    ('Mexican cuisine', 'food_cuisine'),
    ('Indian cuisine', 'food_cuisine'),
    ('Greek mythology', 'mythology_folklore'),
    ('Norse mythology', 'mythology_folklore'),
    ('Myth', 'mythology_folklore'),
    ('Folklore', 'mythology_folklore'),
    ('Zeus', 'mythology_folklore'),
    ('Athena', 'mythology_folklore'),
    ('Poseidon', 'mythology_folklore'),
    ('Odin', 'mythology_folklore'),
    ('Thor', 'mythology_folklore'),
    ('Loki', 'mythology_folklore'),
    ('Dragon', 'mythology_folklore'),
    ('Vampire', 'mythology_folklore'),
    ('Werewolf', 'mythology_folklore'),
    ('Mermaid', 'mythology_folklore'),
    ('Mona Lisa', 'art_literature'),
    ('The Starry Night', 'art_literature'),
    ('The Scream', 'art_literature'),
    ('Vincent van Gogh', 'art_literature'),
    ('Pablo Picasso', 'art_literature'),
    ('Leonardo da Vinci', 'art_literature'),
    ('William Shakespeare', 'art_literature'),
    ('Hamlet', 'art_literature'),
    ('Macbeth', 'art_literature'),
    ('Romeo and Juliet', 'art_literature'),
    ('Harry Potter', 'art_literature'),
    ('The Hobbit', 'art_literature'),
    ('The Lord of the Rings', 'movies'),
    ('Pride and Prejudice', 'art_literature'),
    ('To Kill a Mockingbird', 'art_literature'),
    ("The Legend of Zelda: Majora's Mask", 'video_games'),
    ('The Legend of Zelda: A Link to the Past', 'video_games'),
    ('The Legend of Zelda: The Wind Waker', 'video_games'),
    ('The Legend of Zelda: Twilight Princess', 'video_games'),
    ('The Legend of Zelda: Skyward Sword', 'video_games'),
    ('Super Mario World', 'video_games'),
    ('Super Mario Galaxy', 'video_games'),
    ('Super Mario Galaxy 2', 'video_games'),
    ('Super Mario Sunshine', 'video_games'),
    ('Mario Party', 'video_games'),
    ('Mario Party Superstars', 'video_games'),
    ('Mario Kart Wii', 'video_games'),
    ('Mario Kart 64', 'video_games'),
    ('Paper Mario', 'video_games'),
    ("Luigi's Mansion", 'video_games'),
    ("Luigi's Mansion 3", 'video_games'),
    ('Pokémon Ruby and Sapphire', 'video_games'),
    ('Pokémon Diamond and Pearl', 'video_games'),
    ('Pokémon Black and White', 'video_games'),
    ('Pokémon Sun and Moon', 'video_games'),
    ('Pokémon Legends: Arceus', 'video_games'),
    ('Metroid', 'video_games'),
    ('Super Metroid', 'video_games'),
    ('Metroid Dread', 'video_games'),
    ('Kirby Super Star', 'video_games'),
    ('Kirby and the Forgotten Land', 'video_games'),
    ('Donkey Kong Country', 'geography'),
    ('Donkey Kong Country 2', 'geography'),
    ('F-Zero', 'video_games'),
    ('Fire Emblem: Three Houses', 'video_games'),
    ('Advance Wars', 'video_games'),
    ('EarthBound', 'video_games'),
    ('Mother 3', 'video_games'),
    ('Chrono Trigger', 'video_games'),
    ('Chrono Cross', 'video_games'),
    ('Final Fantasy VI', 'video_games'),
    ('Final Fantasy IX', 'video_games'),
    ('Final Fantasy X', 'video_games'),
    ('Dragon Quest XI', 'video_games'),
    ('Kingdom Hearts II', 'video_games'),
    ('Persona 4', 'video_games'),
    ('Persona 3 Reload', 'video_games'),
    ('Megami Tensei', 'video_games'),
    ('Nier (video game)', 'video_games'),
    ('Octopath Traveler', 'video_games'),
    ('Bravely Default', 'video_games'),
    ('Monster Hunter: World', 'video_games'),
    ('Monster Hunter Rise', 'video_games'),
    ('Resident Evil 2', 'video_games'),
    ('Resident Evil Village', 'video_games'),
    ('Silent Hill', 'video_games'),
    ('Dead Space (2008 video game)', 'video_games'),
    ('Alan Wake', 'video_games'),
    ('Control (video game)', 'video_games'),
    ('The Elder Scrolls III: Morrowind', 'video_games'),
    ('The Elder Scrolls IV: Oblivion', 'video_games'),
    ('Fallout: New Vegas', 'video_games'),
    ('Fallout 4', 'video_games'),
    ('The Witcher 2: Assassins of Kings', 'video_games'),
    ('Cyberpunk: Edgerunners', 'anime_manga'),
    ('Dark Souls II', 'video_games'),
    ('Dark Souls III', 'video_games'),
    ("Demon's Souls", 'video_games'),
    ('Armored Core VI: Fires of Rubicon', 'video_games'),
    ('Hollow Knight: Silksong', 'video_games'),
    ('Celeste 64: Fragments of the Mountain', 'video_games'),
    ('Ori and the Blind Forest', 'geography'),
    ('Ori and the Will of the Wisps', 'video_games'),
    ('Dead by Daylight', 'video_games'),
    ('Risk of Rain 2', 'video_games'),
    ('Spelunky', 'video_games'),
    ('Spelunky 2', 'video_games'),
    ('The Binding of Isaac: Rebirth', 'video_games'),
    ('Enter the Gungeon', 'video_games'),
    ('Inscryption', 'video_games'),
    ('FTL: Faster Than Light', 'video_games'),
    ('Into the Breach', 'video_games'),
    ('Papers, Please', 'video_games'),
    ('Return of the Obra Dinn', 'video_games'),
    ('Factorio', 'video_games'),
    ('Satisfactory', 'video_games'),
    ('RimWorld', 'video_games'),
    ('Kerbal Space Program', 'video_games'),
    ('Noita (video game)', 'video_games'),
    ('Valheim', 'video_games'),
    ('Palworld', 'video_games'),
    ('Vampire Survivors', 'video_games'),
    ('Brotato', 'video_games'),
    ('Peglin', 'video_games'),
    ('Slay the Spire II', 'video_games'),
    ('Half-Life (video game)', 'video_games'),
    ('Half-Life: Alyx', 'video_games'),
    ('Left 4 Dead', 'video_games'),
    ('Counter-Strike 2', 'video_games'),
    ('Team Fortress Classic', 'video_games'),
    ('Quake II', 'video_games'),
    ('Doom II', 'video_games'),
    ('Wolfenstein 3D', 'video_games'),
    ('StarCraft: Brood War', 'video_games'),
    ('Warcraft III: Reign of Chaos', 'video_games'),
    ('Age of Mythology', 'video_games'),
    ('Command & Conquer', 'video_games'),
    ('Civilization V', 'video_games'),
    ('Civilization IV', 'video_games'),
    ('Heroes of Might and Magic III', 'video_games'),
    ('Subnautica: Below Zero', 'video_games'),
    ('XCOM: Enemy Unknown', 'video_games'),
    ('The Sims', 'video_games'),
    ('The Sims 2', 'video_games'),
    ('The Sims 3', 'video_games'),
    ('Cities: Skylines II', 'video_games'),
    ('SimCity 4', 'video_games'),
    ('Euro Truck Simulator 2', 'video_games'),
    ('Gran Turismo 4', 'video_games'),
    ('Forza', 'video_games'),
    ('Need for Speed: Most Wanted', 'video_games'),
    ('Burnout 3: Takedown', 'video_games'),
    ("Tony Hawk's Pro Skater 2", 'video_games'),
    ('SSX 3', 'video_games'),
    ('Wii Sports', 'video_games'),
    ('Wii Sports Resort', 'video_games'),
    ('Clubhouse Games: 51 Worldwide Classics', 'video_games'),
    ('Sorry! (game)', 'board_games'),
    ('Yahtzee', 'board_games'),
    ('Bingo (American version)', 'board_games'),
    ('Yu-Gi-Oh! Trading Card Game', 'board_games'),
    ('Splendor (game)', 'board_games'),
    ('Betrayal at House on the Hill', 'board_games'),
    ('Munchkin (card game)', 'board_games'),
    ('Tabletop game', 'board_games'),
    ('Role-playing game', 'board_games'),
    ('Strategy game', 'board_games'),
    ('Cooperative board game', 'board_games'),
    ('Card game', 'board_games'),
    ('Board game', 'board_games'),
    ('Discord', 'technology'),
    ('Twitch (service)', 'technology'),
    ('Reddit', 'technology'),
    ('Steam Deck', 'video_games'),
    ('Nintendo Switch', 'video_games'),
    ('PlayStation 2', 'video_games'),
    ('PlayStation 5', 'video_games'),
    ('Xbox 360', 'video_games'),
    ('Xbox Series X and Series S', 'video_games'),
    ('GameCube', 'video_games'),
    ('Wii', 'video_games'),
    ('Wii U', 'video_games'),
    ('Nintendo 64', 'video_games'),
    ('Super Nintendo Entertainment System', 'video_games'),
    ('Game Boy', 'video_games'),
    ('Game Boy Advance', 'video_games'),
    ('Nintendo DS', 'video_games'),
    ('PlayStation Portable', 'video_games'),
    ('PlayStation Vita', 'video_games'),
    ('Sega Genesis', 'video_games'),
    ('Dreamcast', 'video_games'),
    ('Atari 2600', 'video_games'),
    ('Arcade game', 'video_games'),
    ('Video game console', 'video_games'),
    ('Handheld game console', 'video_games'),
    ('PC game', 'video_games'),
    ('Esports', 'video_games'),
    ('Speedrunning', 'video_games'),
    ('Video game developer', 'video_games'),
    ('Video game publisher', 'video_games'),
    ('Indie game', 'video_games'),
    ('Game engine', 'video_games'),
    ('Unity (game engine)', 'video_games'),
    ('Unreal Engine 5', 'video_games'),
    ('Source (game engine)', 'video_games'),
    ('Godot (game engine)', 'video_games'),
    ('Open-source software', 'technology'),
    ('Linux', 'technology'),
    ('Windows 11', 'technology'),
    ('macOS', 'technology'),
    ('iOS', 'technology'),
    ('Artificial general intelligence', 'technology'),
    ('Machine learning', 'technology'),
    ('Cloud gaming', 'video_games'),
    ('Virtual reality headset', 'technology'),
    ('Animal Crossing', 'video_games'),
    ('Animal Crossing: Wild World', 'video_games'),
    ('Animal Crossing: New Leaf', 'video_games'),
    ('Banjo-Kazooie', 'video_games'),
    ('Banjo-Tooie', 'video_games'),
    ('Bastion (video game)', 'video_games'),
    ('Bayonetta', 'video_games'),
    ('Bayonetta 2', 'video_games'),
    ('Borderlands 2', 'video_games'),
    ('Borderlands 3', 'video_games'),
    ('Brawl Stars', 'video_games'),
    ('Castlevania', 'video_games'),
    ('Castlevania: Symphony of the Night', 'video_games'),
    ('Crash Bandicoot', 'video_games'),
    ("Crash Bandicoot 4: It's About Time", 'video_games'),
    ('Darkest Dungeon', 'video_games'),
    ('Deus Ex', 'video_games'),
    ('Deus Ex: Human Revolution', 'video_games'),
    ('Dishonored', 'video_games'),
    ('Dishonored 2', 'video_games'),
    ('Dragon Age: Origins', 'video_games'),
    ('Dragon Age: Inquisition', 'video_games'),
    ('Fable II', 'video_games'),
    ('Far Cry 3', 'video_games'),
    ('Far Cry 5', 'video_games'),
    ('For Honor', 'video_games'),
    ('Gears of War', 'video_games'),
    ('Gears 5', 'video_games'),
    ('GoldenEye 007', 'video_games'),
    ('Guilty Gear Strive', 'video_games'),
    ('Hitman (2016 video game)', 'video_games'),
    ('Hitman 3', 'video_games'),
    ('Hotline Miami', 'video_games'),
    ('Hotline Miami 2: Wrong Number', 'video_games'),
    ('Journey (2012 video game)', 'video_games'),
    ('Katamari Damacy', 'video_games'),
    ('Kingdom Come: Deliverance', 'video_games'),
    ('The Stanley Parable', 'video_games'),
    ('LittleBigPlanet', 'science_space'),
    ('LittleBigPlanet 2', 'science_space'),
    ('Mafia II', 'video_games'),
    ('Marvel vs. Capcom 2: New Age of Heroes', 'video_games'),
    ('Mega Man 2', 'video_games'),
    ('Mega Man X', 'video_games'),
    ("Mirror's Edge", 'video_games'),
    ('Mortal Shell', 'video_games'),
    ('Ninja Gaiden', 'video_games'),
    ('Nioh', 'video_games'),
    ('Nioh 2', 'video_games'),
    ('Ōkami', 'video_games'),
    ('Omori (video game)', 'video_games'),
    ('Onimusha', 'video_games'),
    ('Overcooked', 'video_games'),
    ('Overcooked 2', 'video_games'),
    ('Paladins (video game)', 'video_games'),
    ('Path of Exile', 'video_games'),
    ('Plants vs. Zombies', 'video_games'),
    ('Prey (2017 video game)', 'video_games'),
    ('Prince of Persia: The Sands of Time', 'video_games'),
    ('Psychonauts', 'video_games'),
    ('Psychonauts 2', 'video_games'),
    ('Rayman Legends', 'video_games'),
    ('Rayman Origins', 'video_games'),
    ('Returnal', 'video_games'),
    ('Shovel Knight', 'video_games'),
    ('Skate 3', 'video_games'),
    ('Skullgirls', 'video_games'),
    ('Sly Cooper and the Thievius Raccoonus', 'video_games'),
    ('Sonic Adventure 2', 'video_games'),
    ('Sonic Mania', 'video_games'),
    ('Soulcalibur II', 'video_games'),
    ('Star Fox 64', 'video_games'),
    ('Star Wars Jedi: Fallen Order', 'movies'),
    ('Star Wars Jedi: Survivor', 'movies'),
    ('Sunset Overdrive', 'video_games'),
    ('The Talos Principle', 'video_games'),
    ('The World Ends with You', 'video_games'),
    ('Titanfall 2', 'video_games'),
    ("Tom Clancy's Rainbow Six Siege", 'video_games'),
    ('Torchlight II', 'video_games'),
    ('Transistor (video game)', 'video_games'),
    ('Warcraft II: Tides of Darkness', 'video_games'),
    ('Wasteland 3', 'video_games'),
    ('Xenoblade', 'video_games'),
    ('Xenoblade Chronicles 2', 'video_games'),
    ('Yakuza 0', 'video_games'),
    ('Yakuza: Like a Dragon', 'video_games'),
    ("Zero Escape: Virtue's Last Reward", 'video_games'),
    ('A Game of Thrones (board game)', 'board_games'),
    ('Agricola (board game)', 'board_games'),
    ('Arkham Horror', 'board_games'),
    ('Bang! (card game)', 'board_games'),
    ('Blood Rage (board game)', 'board_games'),
    ('Brass (board game)', 'board_games'),
    ('Camel Up', 'board_games'),
    ('Captain Sonar', 'board_games'),
    ('Cascadia (board game)', 'board_games'),
    ('Citadels (card game)', 'board_games'),
    ('Cosmic Encounter', 'board_games'),
    ('Coup (card game)', 'board_games'),
    ('Deck-building game', 'board_games'),
    ('List of dice games', 'board_games'),
    ('Dixit (board game)', 'board_games'),
    ('Eldritch Horror', 'board_games'),
    ('Forbidden Island (game)', 'geography'),
    ('Forbidden Desert', 'geography'),
    ('Hive (game)', 'board_games'),
    ('King of Tokyo', 'board_games'),
    ('Love Letter (card game)', 'board_games'),
    ('Ludo', 'board_games'),
    ('Mastermind (board game)', 'board_games'),
    ('Meeple', 'board_games'),
    ('Race for the Galaxy', 'science_space'),
    ('Santorini (game)', 'board_games'),
    ('Scythe (board game)', 'board_games'),
    ('Sequence (game)', 'board_games'),
    ('Skull (card game)', 'board_games'),
    ('Small World (board game)', 'board_games'),
    ('The Crew (card game)', 'board_games'),
    ('Trivial Pursuit', 'board_games'),
    ('Twilight Imperium', 'board_games'),
    ('Word game', 'board_games'),
    ('Zombicide', 'board_games'),
    ('A Quiet Place', 'movies'),
    ('Alien (film)', 'movies'),
    ('Aliens (film)', 'movies'),
    ('Arrival (film)', 'movies'),
    ('Blade Runner', 'movies'),
    ('Blade Runner 2049', 'movies'),
    ('Catch Me If You Can', 'movies'),
    ('Coraline (film)', 'movies'),
    ('Doctor Strange (2016 film)', 'movies'),
    ('Donnie Darko', 'movies'),
    ('Edge of Tomorrow', 'movies'),
    ('Everything Everywhere All at Once', 'movies'),
    ('Finding Dory', 'movies'),
    ('Her (2013 film)', 'movies'),
    ('How to Train Your Dragon (2010 film)', 'movies'),
    ("Howl's Moving Castle (film)", 'movies'),
    ('John Wick', 'movies'),
    ('John Wick: Chapter 4', 'movies'),
    ('Kill Bill: Volume 1', 'movies'),
    ('Knives Out', 'movies'),
    ('Madagascar (2005 film)', 'movies'),
    ('Mean Girls', 'movies'),
    ('Mission: Impossible – Fallout', 'video_games'),
    ('Monsters, Inc.', 'movies'),
    ('Night at the Museum', 'art_literature'),
    ('No Country for Old Men', 'geography'),
    ('Parasite (2019 film)', 'movies'),
    ('Ratatouille (film)', 'movies'),
    ('Ready Player One (film)', 'movies'),
    ('School of Rock', 'movies'),
    ('Shrek 2', 'movies'),
    ('Spider-Man 2', 'movies'),
    ('Spirited Away', 'movies'),
    ('The Batman (film)', 'movies'),
    ('The Grand Budapest Hotel', 'movies'),
    ('The Hunger Games (film)', 'movies'),
    ('The Lego Movie', 'movies'),
    ('The Martian (film)', 'movies'),
    ('The Prestige', 'movies'),
    ('The Truman Show', 'movies'),
    ('Up (2009 film)', 'movies'),
    ('WALL-E', 'movies'),
    ('Wreck-It Ralph', 'movies'),
    ('X-Men: Days of Future Past', 'movies'),
    ('Arrested Development', 'tv_shows'),
    ('BoJack Horseman', 'tv_shows'),
    ('Buffy the Vampire Slayer', 'tv_shows'),
    ('Community (TV series)', 'tv_shows'),
    ('Futurama', 'tv_shows'),
    ('Gilmore Girls', 'tv_shows'),
    ('Glee (TV series)', 'tv_shows'),
    ('Hannibal (TV series)', 'tv_shows'),
    ('Heartstopper (TV series)', 'tv_shows'),
    ("It's Always Sunny in Philadelphia", 'tv_shows'),
    ('Jane the Virgin', 'tv_shows'),
    ('Killing Eve', 'tv_shows'),
    ('Lost in Space (2018 TV series)', 'tv_shows'),
    ('Lucifer (TV series)', 'tv_shows'),
    ('Malcolm in the Middle', 'tv_shows'),
    ('Mr. Robot', 'tv_shows'),
    ('MythBusters', 'tv_shows'),
    ('Only Murders in the Building', 'tv_shows'),
    ('Ozark (TV series)', 'tv_shows'),
    ('Psych', 'tv_shows'),
    ('Scrubs (TV series)', 'tv_shows'),
    ('Sex Education (TV series)', 'tv_shows'),
    ('Suits (American TV series)', 'tv_shows'),
    ('Supernatural (American TV series)', 'tv_shows'),
    ('The Good Place', 'tv_shows'),
    ('The Haunting of Hill House', 'tv_shows'),
    ('The IT Crowd', 'tv_shows'),
    ('The Leftovers (TV series)', 'tv_shows'),
    ('The Owl House', 'tv_shows'),
    ('The X-Files', 'tv_shows'),
    ('Twin Peaks', 'tv_shows'),
    ('What We Do in the Shadows (TV series)', 'tv_shows'),
    ("X-Men '97", 'tv_shows'),
    ('Assassination Classroom', 'anime_manga'),
    ('Berserk (manga)', 'anime_manga'),
    ('Black Clover', 'anime_manga'),
    ('Chainsaw Man', 'anime_manga'),
    ('Code Geass', 'anime_manga'),
    ('Dandadan', 'anime_manga'),
    ('Dr. Stone', 'anime_manga'),
    ('Fairy Tail', 'anime_manga'),
    ('Frieren', 'anime_manga'),
    ('Gintama', 'anime_manga'),
    ('Haikyu!!', 'anime_manga'),
    ('Hellsing', 'anime_manga'),
    ('Inuyasha', 'anime_manga'),
    ("JoJo's Bizarre Adventure", 'anime_manga'),
    ('Kaguya-sama: Love Is War', 'anime_manga'),
    ('Mob Psycho 100', 'anime_manga'),
    ('Monster (manga)', 'anime_manga'),
    ('Mushoku Tensei', 'anime_manga'),
    ('One-Punch Man', 'anime_manga'),
    ('Parasyte', 'anime_manga'),
    ('Pokémon (TV series)', 'tv_shows'),
    ('Re:Zero', 'anime_manga'),
    ('Samurai Champloo', 'anime_manga'),
    ('Solo Leveling', 'anime_manga'),
    ('Spy × Family', 'anime_manga'),
    ('Steins;Gate', 'anime_manga'),
    ('The Apothecary Diaries', 'anime_manga'),
    ('Tokyo Revengers', 'anime_manga'),
    ('Trigun', 'anime_manga'),
    ('Vinland Saga (manga)', 'anime_manga'),
    ('Volleyball', 'sports'),
    ('Ice hockey', 'sports'),
    ('National Hockey League', 'sports'),
    ('College football', 'sports'),
    ('College basketball', 'sports'),
    ('Rugby union', 'sports'),
    ('Rugby World Cup', 'sports'),
    ('Boxing', 'sports'),
    ('Mixed martial arts', 'sports'),
    ('Ultimate Fighting Championship', 'sports'),
    ('Professional wrestling', 'sports'),
    ('Table tennis', 'sports'),
    ('Badminton', 'sports'),
    ('Sport of athletics', 'sports'),
    ('Track and field', 'sports'),
    ('Marathon', 'sports'),
    ('Competitive swimming', 'sports'),
    ('Gymnastics', 'sports'),
    ('Skateboarding', 'sports'),
    ('Snowboarding', 'sports'),
    ('Skiing', 'sports'),
    ('Surfing', 'sports'),
    ('World Series', 'sports'),
    ('Stanley Cup', 'sports'),
    ('UEFA European Championship', 'sports'),
    ('Copa América', 'sports'),
    ('Albert Einstein', 'science_space'),
    ('Isaac Newton', 'science_space'),
    ('Nikola Tesla', 'science_space'),
    ('Marie Curie', 'science_space'),
    ('Charles Darwin', 'science_space'),
    ('Stephen Hawking', 'science_space'),
    ('Galileo Galilei', 'science_space'),
    ('Quantum mechanics', 'science_space'),
    ('General relativity', 'science_space'),
    ('Theory of relativity', 'science_space'),
    ('Cell (biology)', 'science_space'),
    ('Photosynthesis', 'science_space'),
    ('Natural selection', 'science_space'),
    ('Evolution', 'science_space'),
    ('Climate change', 'science_space'),
    ('Oceanography', 'geography'),
    ('Ecology', 'science_space'),
    ('Paleontology', 'science_space'),
    ('Dinosaur', 'science_space'),
    ('Tyrannosaurus', 'science_space'),
    ('Triceratops', 'science_space'),
    ('SpaceX', 'science_space'),
    ('NASA', 'science_space'),
    ('Apollo program', 'science_space'),
    ('Venus', 'science_space'),
    ('Mercury (planet)', 'science_space'),
    ('Neptune', 'science_space'),
    ('Uranus', 'science_space'),
    ('Pluto', 'science_space'),
    ('Exoplanet', 'science_space'),
    ('Computer science', 'technology'),
    ('JavaScript', 'technology'),
    ('Python (programming language)', 'technology'),
    ('Java (programming language)', 'technology'),
    ('Git', 'technology'),
    ('GitHub', 'technology'),
    ('Web development', 'technology'),
    ('Front end and back end', 'technology'),
    ('Search engine', 'technology'),
    ('Streaming media', 'technology'),
    ('Netflix', 'technology'),
    ('Spotify', 'technology'),
    ('Email', 'technology'),
    ('Wireless network', 'technology'),
    ('Bluetooth', 'technology'),
    ('USB', 'technology'),
    ('Laptop', 'technology'),
    ('Desktop computer', 'technology'),
    ('Microprocessor', 'technology'),
    ('Graphics processing unit', 'technology'),
    ('Semiconductor', 'technology'),
    ('Computer security', 'technology'),
    ('Deep learning', 'technology'),
    ('Ancient Rome', 'history'),
    ('Byzantine Empire', 'history'),
    ('Ottoman Empire', 'history'),
    ('Mongol Empire', 'history'),
    ('French Revolution', 'history'),
    ('American Revolution', 'history'),
    ('Victorian era', 'history'),
    ('Stone Age', 'history'),
    ('Bronze Age', 'history'),
    ('Iron Age', 'history'),
    ('Age of Discovery', 'history'),
    ('Space Race', 'history'),
    ('Great Depression', 'history'),
    ('Roaring Twenties', 'history'),
    ('Feudalism', 'history'),
    ('Magna Carta', 'history'),
    ('Berlin Wall', 'history'),
    ('Norman Conquest', 'history'),
    ('Crusades', 'history'),
    ('Printing press', 'history'),
    ('Titanic', 'movies'),
    ('Steam engine', 'technology'),
    ('Asia', 'geography'),
    ('Europe', 'geography'),
    ('Africa', 'geography'),
    ('North America', 'geography'),
    ('South America', 'geography'),
    ('Australia', 'geography'),
    ('Antarctica', 'geography'),
    ('Japan', 'geography'),
    ('United States', 'geography'),
    ('Canada', 'geography'),
    ('Mexico', 'geography'),
    ('Brazil', 'geography'),
    ('United Kingdom', 'geography'),
    ('Germany', 'geography'),
    ('Italy', 'geography'),
    ('Spain', 'geography'),
    ('China', 'geography'),
    ('South Korea', 'geography'),
    ('India', 'geography'),
    ('Egypt', 'geography'),
    ('Mount Fuji', 'geography'),
    ('Grand Canyon', 'geography'),
    ('Niagara Falls', 'geography'),
    ('Yellowstone National Park', 'geography'),
    ('Mount Kilimanjaro', 'geography'),
    ('Great Barrier Reef', 'geography'),
    ('Mediterranean Sea', 'geography'),
    ('Arctic Ocean', 'geography'),
    ('Ring of Fire', 'geography'),
    ('Sicily', 'geography'),
    ('Hawaii', 'geography'),
    ('Bread', 'food_cuisine'),
    ('Cake', 'food_cuisine'),
    ('Cookie', 'food_cuisine'),
    ('Dumpling', 'food_cuisine'),
    ('Burrito', 'food_cuisine'),
    ('Nachos', 'food_cuisine'),
    ('Lasagna', 'food_cuisine'),
    ('Spaghetti', 'food_cuisine'),
    ('Curry', 'food_cuisine'),
    ('Fried rice', 'food_cuisine'),
    ('Noodle', 'food_cuisine'),
    ('Soup', 'food_cuisine'),
    ('Salad', 'food_cuisine'),
    ('Steak', 'food_cuisine'),
    ('Pancake', 'food_cuisine'),
    ('Waffle', 'food_cuisine'),
    ('French fries', 'food_cuisine'),
    ('Milkshake', 'food_cuisine'),
    ('Cheesecake', 'food_cuisine'),
    ('Sashimi', 'food_cuisine'),
    ('Tempura', 'food_cuisine'),
    ('Falafel', 'food_cuisine'),
    ('Croissant', 'food_cuisine'),
    ('Espresso', 'food_cuisine'),
    ('Soft drink', 'food_cuisine'),
    ('Breakfast', 'food_cuisine'),
    ('Lunch', 'food_cuisine'),
    ('Dinner', 'food_cuisine'),
    ('Odyssey', 'art_literature'),
    ('Iliad', 'art_literature'),
    ('Divine Comedy', 'art_literature'),
    ('Don Quixote', 'art_literature'),
    ('Frankenstein', 'art_literature'),
    ('Dracula', 'art_literature'),
    ('Moby-Dick', 'art_literature'),
    ('The Great Gatsby', 'art_literature'),
    ('Nineteen Eighty-Four', 'art_literature'),
    ('Animal Farm', 'art_literature'),
    ('The Catcher in the Rye', 'art_literature'),
    ('Jane Austen', 'art_literature'),
    ('Mark Twain', 'art_literature'),
    ('Charles Dickens', 'art_literature'),
    ('Edgar Allan Poe', 'art_literature'),
    ('J. R. R. Tolkien', 'art_literature'),
    ('George Orwell', 'art_literature'),
    ('Fyodor Dostoevsky', 'art_literature'),
    ('Claude Monet', 'art_literature'),
    ('Michelangelo', 'art_literature'),
    ('Rembrandt', 'art_literature'),
    ('Salvador Dalí', 'art_literature'),
    ('The Last Supper (Leonardo)', 'art_literature'),
    ('Girl with a Pearl Earring', 'art_literature'),
    ('Roman mythology', 'mythology_folklore'),
    ('Egyptian mythology', 'mythology_folklore'),
    ('Japanese mythology', 'mythology_folklore'),
    ('Celtic mythology', 'mythology_folklore'),
    ('Hades', 'mythology_folklore'),
    ('Ares', 'mythology_folklore'),
    ('Hercules', 'mythology_folklore'),
    ('Achilles', 'mythology_folklore'),
    ('Perseus', 'mythology_folklore'),
    ('Medusa', 'mythology_folklore'),
    ('Pegasus', 'mythology_folklore'),
    ('Minotaur', 'mythology_folklore'),
    ('Cyclopes', 'mythology_folklore'),
    ('Phoenix (mythology)', 'mythology_folklore'),
    ('Kraken', 'mythology_folklore'),
    ('Basilisk', 'mythology_folklore'),
    ('Fairy', 'mythology_folklore'),
    ('Ghost', 'mythology_folklore'),
    ('Steven Spielberg', 'movies'),
    ('Wordle', 'video_games'),
    ('Grand Theft Auto VI', 'video_games'),
    ('The Super Mario Galaxy Movie', 'movies'),
    ('Uwe Boll', 'movies'),
    ('IShowSpeed', 'technology'),
    ('God of War (franchise)', 'video_games'),
    ('Toy Story (franchise)', 'movies'),
    ('Hasan Piker', 'technology'),
    ('Asha Sharma', 'technology'),
    ('Alan Turing', 'science_space'),
    ('Resident Evil – Code: Veronica', 'video_games'),
    ('Meccha Chameleon', 'video_games'),
    ('Nvidia', 'technology'),
    ('Grand Theft Auto', 'video_games'),
    ('Apple Inc.', 'technology'),
    ('Call of Duty', 'video_games'),
    ('Characters of the Mortal Kombat series', 'video_games'),
    ('Resident Evil', 'video_games'),
    ('Microsoft', 'technology'),
    ('Mobile app', 'technology'),
    ('Ubisoft', 'video_games'),
    ('Rockstar Games', 'video_games'),
    ('Tarot', 'board_games'),
    ('Major Arcana', 'board_games'),
    ('Elo rating system', 'board_games'),
    ('Blackjack', 'board_games'),
    ('Mattel', 'board_games'),
    ('Roulette', 'board_games'),
    ('Game', 'board_games'),
    ('Hasbro', 'board_games'),
    ('Tic-tac-toe', 'board_games'),
    ('Grandmaster (chess)', 'board_games'),
    ('Rummy', 'board_games'),
    ('Playing card', 'board_games'),
    ('Klondike (solitaire)', 'board_games'),
    ('Standard 52-card deck', 'board_games'),
    ('Contract bridge', 'board_games'),
    ('Warhammer (game)', 'board_games'),
    ('Illuminati: New World Order', 'board_games'),
    ('Rummikub', 'board_games'),
    ('Wizards of the Coast', 'board_games'),
    ('Trench Crusade', 'board_games'),
    ('Dice', 'board_games'),
    ('Games Workshop', 'board_games'),
    ('Toy Story 5', 'movies'),
    ('XXX (film series)', 'movies'),
    ('Callum Turner', 'movies'),
    ('The Mandalorian and Grogu', 'movies'),
    ('Project Hail Mary (film)', 'movies'),
    ('Spider-Man: Brand New Day', 'movies'),
    ("Widow's Bay", 'tv_shows'),
    ('Anthony Head', 'tv_shows'),
    ('I Will Find You', 'tv_shows'),
    ('Donald Trump', 'history'),
    ('Off Campus', 'tv_shows'),
    ('Teach You a Lesson', 'tv_shows'),
    ('Spider-Noir', 'tv_shows'),
    ('Dutton Ranch', 'tv_shows'),
    ('From (TV series)', 'tv_shows'),
    ('The Boroughs', 'tv_shows'),
    ('Cape Fear (TV series)', 'tv_shows'),
    ('Tip Toe (TV series)', 'tv_shows'),
    ('Ariana Grande', 'music'),
    ('The Four Seasons (TV series)', 'tv_shows'),
    ('Every Year After', 'tv_shows'),
    ('Sydney Sweeney', 'tv_shows'),
    ('Penelope Keith', 'tv_shows'),
    ('Death of Michael Jackson', 'music'),
    ('Milo Ventimiglia', 'tv_shows'),
    ('Rivals (TV series)', 'tv_shows'),
    ('Scott Pelley', 'tv_shows'),
    ('Olivia Wilde', 'tv_shows'),
    ('Morena Baccarin', 'tv_shows'),
    ('Not Suitable for Work', 'tv_shows'),
    ('Your Friends & Neighbors (TV series)', 'tv_shows'),
    ('Jordyn Woods', 'tv_shows'),
    ('For All Mankind (TV series)', 'tv_shows'),
    ('Harry Styles', 'music'),
    ('Half Man (TV series)', 'tv_shows'),
    ('DC Universe (franchise)', 'tv_shows'),
    ('Jason Momoa', 'tv_shows'),
    ('Gene Shalit', 'tv_shows'),
    ('Yellowstone (TV series)', 'tv_shows'),
    ('Interview with the Vampire (TV series)', 'tv_shows'),
    ('The Pitt', 'tv_shows'),
    ("Clarkson's Farm", 'tv_shows'),
    ('Smoking Behind the Supermarket with You', 'anime_manga'),
    ('Witch Hat Atelier', 'anime_manga'),
    ('Anime', 'anime_manga'),
    ('Daemons of the Shadow Realm', 'anime_manga'),
    ('Studio Ghibli', 'anime_manga'),
    ('Pokémon', 'anime_manga'),
    ('Jimoto Saiko!', 'anime_manga'),
    ('Laura Bailey', 'anime_manga'),
    ('Wistoria: Wand and Sword', 'anime_manga'),
    ('Hayao Miyazaki', 'anime_manga'),
    ('Hatsune Miku', 'anime_manga'),
    ('The Ramparts of Ice', 'anime_manga'),
    ('Go for It, Nakamura!', 'anime_manga'),
    ('Matthew Mercer', 'video_games'),
    ('Pikachu', 'anime_manga'),
    ('Manga', 'anime_manga'),
    ('Grave of the Fireflies', 'anime_manga'),
    ('Travis Willingham', 'video_games'),
    ('Tara Strong', 'tv_shows'),
    ('Bleach: Thousand-Year Blood War', 'anime_manga'),
    ('Persona 4 Revival', 'video_games'),
    ('Princess Mononoke', 'anime_manga'),
    ('Nippon Sangoku', 'anime_manga'),
    ('Lizzie Freeman', 'anime_manga'),
    ('Re:Zero season 4', 'anime_manga'),
    ('Blue Lock', 'anime_manga'),
    ('Troy Baker', 'video_games'),
    ('Attack on Titan (TV series)', 'anime_manga'),
    ('Marriagetoxin', 'anime_manga'),
    ('Hello Kitty', 'anime_manga'),
    ('The Boy and the Heron', 'anime_manga'),
    ('My Neighbor Totoro', 'anime_manga'),
    ('Gachiakuta', 'anime_manga'),
    ('Gundam', 'anime_manga'),
    ('Touhou Project', 'anime_manga'),
    ('Your Name', 'anime_manga'),
    ('Gokusen', 'anime_manga'),
    ('Bilibili', 'anime_manga'),
    ('Ghost in the Shell', 'anime_manga'),
    ('Baki the Grappler', 'anime_manga'),
    ("Boys' love", 'anime_manga'),
    ('My Dress-Up Darling', 'anime_manga'),
    ('Boku no Pico', 'anime_manga'),
    ('Ponyo', 'anime_manga'),
    ('Dorohedoro', 'anime_manga'),
    ('Agents of the Four Seasons', 'anime_manga'),
    ('Perfect Blue', 'anime_manga'),
    ('Futanari', 'anime_manga'),
    ('The Summer Hikaru Died', 'anime_manga'),
    ('Alita: Battle Angel', 'anime_manga'),
    ('Jujutsu Kaisen (TV series)', 'anime_manga'),
    ('Alexi Lalas', 'sports'),
    ('MetLife Stadium', 'sports'),
    ('Estadio Azteca', 'sports'),
    ('Exhibition game', 'sports'),
    ('Gillette Stadium', 'sports'),
    ('NBA Finals', 'sports'),
    ('TNT Sports (United Kingdom)', 'sports'),
    ('Marty Supreme', 'movies'),
    ('French Open', 'sports'),
    ('BMO Field', 'sports'),
    ('Major League Soccer', 'sports'),
    ('La Liga', 'sports'),
    ('Gregg Popovich', 'sports'),
    ('FIFA Club World Cup', 'sports'),
    ('Lumen Field', 'sports'),
    ('EFL Championship', 'sports'),
    ("Levi's Stadium", 'sports'),
    ('Cricket', 'sports'),
    ('Estadio Akron', 'sports'),
    ('Mercedes-Benz Stadium', 'sports'),
    ('Estadio BBVA', 'sports'),
    ('Ligue 1', 'sports'),
    ('Serie A', 'sports'),
    ('Bundesliga', 'sports'),
    ('Hard Rock Stadium', 'sports'),
    ('Limonene', 'food_cuisine'),
    ('Anthony Bourdain', 'food_cuisine'),
    ('Kyle Busch', 'food_cuisine'),
    ('Teetotalism', 'food_cuisine'),
    ('Gordon Ramsay', 'food_cuisine'),
    ("San Ysidro McDonald's massacre", 'food_cuisine'),
    ('Jared Fogle', 'food_cuisine'),
    ("McDonald's", 'food_cuisine'),
    ('Geheimrat Dr. Oldenburg', 'food_cuisine'),
    ('Curaçao (liqueur)', 'food_cuisine'),
    ('Martha Stewart', 'food_cuisine'),
    ('Pot-au-feu', 'food_cuisine'),
    ('Padma Lakshmi', 'food_cuisine'),
    ('Chocolate-coated marshmallow treats', 'food_cuisine'),
    ("Buc-ee's", 'food_cuisine'),
    ('Coca-Cola', 'food_cuisine'),
    ('Colonel Sanders', 'food_cuisine'),
    ('Pescetarianism', 'food_cuisine'),
    ('Marco Pierre White', 'food_cuisine'),
    ('Human cannibalism', 'food_cuisine'),
    ('Valerie Bertinelli', 'food_cuisine'),
    ('Dionysus', 'mythology_folklore'),
    ('Kimbal Musk', 'food_cuisine'),
    ('Apple', 'food_cuisine'),
    ('Jessica Seinfeld', 'food_cuisine'),
    ('Water', 'food_cuisine'),
    ('LVMH', 'food_cuisine'),
    ('Cheers', 'food_cuisine'),
    ('Yevgeny Prigozhin', 'food_cuisine'),
    ('Red Bull', 'food_cuisine'),
    ('Ranch dressing', 'food_cuisine'),
    ('Matty Matheson', 'food_cuisine'),
    ('MasterChef (American TV series) season 16', 'food_cuisine'),
    ('Fish', 'food_cuisine'),
    ('Lychee', 'food_cuisine'),
    ('Julia Child', 'food_cuisine'),
    ('Ray Kroc', 'food_cuisine'),
    ('Rabbit', 'food_cuisine'),
    ('Banana', 'food_cuisine'),
    ('Yum! Brands', 'food_cuisine'),
    ('Starbucks', 'food_cuisine'),
    ('Aldi', 'food_cuisine'),
    ('Matcha', 'food_cuisine'),
    ('Breyers', 'food_cuisine'),
    ('KFC', 'food_cuisine'),
    ('Nick DiGiovanni', 'food_cuisine'),
    ('Bobby Flay', 'food_cuisine'),
    ('Prohibition in the United States', 'food_cuisine'),
    ('Tiramisu', 'food_cuisine'),
    ('Jägermeister', 'food_cuisine'),
    ('Liver King', 'food_cuisine'),
    ('Nestlé', 'food_cuisine'),
    ('Kopi luwak', 'food_cuisine'),
    ('Surströmming', 'food_cuisine'),
    ('PepsiCo', 'food_cuisine'),
    ('The Great British Bake Off', 'food_cuisine'),
    ('Cicada', 'food_cuisine'),
    ('Guy Fieri', 'food_cuisine'),
    ('Potato', 'food_cuisine'),
    ('Michelin Guide', 'food_cuisine'),
    ('Ethanol', 'food_cuisine'),
    ('Dr Pepper', 'food_cuisine'),
    ('Tomato', 'food_cuisine'),
    ('Foie gras', 'food_cuisine'),
    ('Pig', 'food_cuisine'),
    ('Maize', 'food_cuisine'),
    ('Ginkgo biloba', 'food_cuisine'),
    ('Ayahuasca', 'food_cuisine'),
    ('Yerba mate', 'food_cuisine'),
    ('Avocado', 'food_cuisine'),
    ('Cassava', 'food_cuisine'),
    ('Mangosteen', 'food_cuisine'),
    ('Pierogi', 'food_cuisine'),
    ('Kombucha', 'food_cuisine'),
    ('Guinea pig', 'food_cuisine'),
    ('Absinthe', 'food_cuisine'),
    ('Mars Inc.', 'food_cuisine'),
    ('The Coca-Cola Company', 'food_cuisine'),
    ('Vegemite', 'food_cuisine'),
    ('Wild boar', 'food_cuisine'),
    ("Hell's Kitchen (American TV series)", 'food_cuisine'),
    ('Haggis', 'food_cuisine'),
    ('Goat', 'food_cuisine'),
    ('Pizza Hut', 'food_cuisine'),
    ('Plant', 'food_cuisine'),
    ('Unilever', 'food_cuisine'),
    ('Piña colada', 'food_cuisine'),
    ('Zongzi', 'food_cuisine'),
    ('Monster Energy', 'food_cuisine'),
    ('Durian', 'food_cuisine'),
    ('Strawberry', 'food_cuisine'),
    ('Dom DeLuise', 'food_cuisine'),
    ('Monosodium glutamate', 'food_cuisine'),
    ("Angus Barbieri's fast", 'food_cuisine'),
    ('Mango', 'food_cuisine'),
    ('Kefir', 'food_cuisine'),
    ('Caesar salad', 'food_cuisine'),
    ('Pepsi', 'food_cuisine'),
    ('Moringa oleifera', 'food_cuisine'),
    ('Watermelon', 'food_cuisine'),
    ('Quince', 'food_cuisine'),
    ('Red Bull GmbH', 'food_cuisine'),
    ('Goyslop', 'food_cuisine'),
    ('Salvia', 'food_cuisine'),
    ('Cashew', 'food_cuisine'),
    ('MasterChef Australia', 'food_cuisine'),
    ('Nigella Lawson', 'food_cuisine'),
    ('Anglerfish', 'food_cuisine'),
    ('Prue Leith', 'food_cuisine'),
    ('Pineapple', 'food_cuisine'),
    ('Shawarma', 'food_cuisine'),
    ('Rhubarb', 'food_cuisine'),
    ('Horchata', 'food_cuisine'),
    ('Caffeine', 'food_cuisine'),
    ('MasterChef (American TV series)', 'food_cuisine'),
    ('Orange (fruit)', 'food_cuisine'),
    ('Flowering plant', 'food_cuisine'),
    ('Umami', 'food_cuisine'),
    ('Camel', 'food_cuisine'),
    ("Luby's shooting", 'food_cuisine'),
    ('Margarine', 'food_cuisine'),
    ('Mondelez International', 'food_cuisine'),
    ('Long Island iced tea', 'food_cuisine'),
    ('Peanut', 'food_cuisine'),
    ('Vietnam War', 'history'),
    ('Soviet Union', 'history'),
    ('The Holocaust', 'history'),
    ('Che Guevara', 'history'),
    ('Nazi Germany', 'history'),
    ('Catholic Church', 'history'),
    ('American Revolutionary War', 'history'),
    ('Nelson Mandela', 'history'),
    ('Christopher Columbus', 'history'),
    ('Holy Roman Empire', 'history'),
    ('The Buddha', 'history'),
    ('Marcus Aurelius', 'history'),
    ('Baháʼí Faith', 'history'),
    ('British Empire', 'history'),
    ('Confederate States of America', 'history'),
    ('Battle of Midway', 'history'),
    ('Apartheid', 'history'),
    ('Assassination of John F. Kennedy', 'history'),
    ('Achaemenid Empire', 'history'),
    ('Mobutu Sese Seko', 'history'),
    ('East India Company', 'history'),
    ('Jerusalem', 'history'),
    ('Independence Day (United States)', 'history'),
    ('Socialism', 'history'),
    ('King Arthur', 'mythology_folklore'),
    ('Russian Empire', 'history'),
    ('Mesopotamia', 'history'),
    ('British Raj', 'history'),
    ('Nikita Khrushchev', 'history'),
    ('Golda Meir', 'history'),
    ('Constantine the Great', 'history'),
    ('Thirteen Colonies', 'history'),
    ('Nazi Party', 'history'),
    ('Second presidency of Donald Trump', 'history'),
    ('Leonid Brezhnev', 'history'),
    ("Thirty Years' War", 'history'),
    ('Communism', 'history'),
    ('Empire of Japan', 'history'),
    ('John Wilkes Booth', 'history'),
    ('Puyi', 'history'),
    ('Agnosticism', 'history'),
    ('Attila', 'history'),
    ('Weimar Republic', 'history'),
    ('Venezuela', 'geography'),
    ('England', 'geography'),
    ('Washington, D.C.', 'geography'),
    ('Hong Kong', 'geography'),
    ('Generation Z', 'geography'),
    ('Mexico City', 'geography'),
    ('Strait of Hormuz', 'geography'),
    ('Puerto Rico', 'geography'),
    ('Generation X', 'geography'),
    ('Google Maps', 'geography'),
    ('Continent', 'geography'),
    ('Millennials', 'geography'),
    ('Cuba', 'geography'),
    ('Berlin', 'geography'),
    ('Generation Alpha', 'geography'),
    ('Google Earth', 'geography'),
    ('Macau', 'geography'),
    ('Balkans', 'geography'),
    ('Patagonia', 'geography'),
    ('Chongqing', 'geography'),
    ('Oceania', 'geography'),
    ('Shanghai', 'geography'),
    ('Beijing', 'geography'),
    ('Guam', 'geography'),
    ('Herzegovina', 'geography'),
    ('.xyz', 'technology'),
    ('ChatGPT', 'technology'),
    ('Jeff Bezos', 'technology'),
    ('JSON-LD', 'technology'),
    ('Microdata (HTML)', 'technology'),
    ('RDFa', 'technology'),
    ('Facebook', 'technology'),
    ('QR code', 'technology'),
    ('WhatsApp', 'technology'),
    ('Wiki', 'technology'),
    ('Anthropic', 'technology'),
    ('The Social Reckoning', 'technology'),
    ('X (social network)', 'technology'),
    ('Steve Jobs', 'technology'),
    ('Elon Musk', 'science_space'),
    ('Wealth of Elon Musk', 'science_space'),
    ('Star City (TV series)', 'tv_shows'),
    ('Sun', 'science_space'),
    ('Summer solstice', 'science_space'),
    ('Lyndon B. Johnson', 'history'),
    ('William Shatner', 'tv_shows'),
    ('Wet-bulb temperature', 'science_space'),
    ('J. Robert Oppenheimer', 'science_space'),
    ('Artemis III', 'science_space'),
    ('Gwynne Shotwell', 'science_space'),
    ('Chicxulub crater', 'science_space'),
    ('Starlink', 'science_space'),
    ('Brian May', 'music'),
    ('A. P. J. Abdul Kalam', 'science_space'),
    ('Space Shuttle Challenger disaster', 'science_space'),
    ('Neil deGrasse Tyson', 'science_space'),
    ('Neil Armstrong', 'science_space'),
    ('Ansel Adams', 'art_literature'),
    ('David Hockney', 'art_literature'),
    ('Dungeon Crawler Carl', 'art_literature'),
    ('Liminal space', 'mythology_folklore'),
    ('Jacqueline Kennedy Onassis', 'art_literature'),
    ('Creepypasta', 'mythology_folklore'),
    ('Emma Watson', 'art_literature'),
    ('Ralph Fiennes', 'art_literature'),
    ('Wuthering Heights', 'art_literature'),
    ('Rama Duwaji', 'art_literature'),
    ('Emma Thompson', 'art_literature'),
    ('Klara and the Sun', 'art_literature'),
    ('Abigail Thorn', 'art_literature'),
    ('Ernest Hemingway', 'art_literature'),
    ('Frida Kahlo', 'art_literature'),
    ('Roald Dahl', 'art_literature'),
    ('Daniel Radcliffe', 'art_literature'),
    ('John Williams', 'art_literature'),
    ('Richard Gadd', 'art_literature'),
    ('Flowers in the Attic', 'art_literature'),
    ('Andy Warhol', 'art_literature'),
    ('Gary Oldman', 'art_literature'),
    ('A Song of Ice and Fire', 'art_literature'),
    ('Brendan Gleeson', 'art_literature'),
    ('John Lithgow', 'art_literature'),
    ('J. K. Rowling', 'art_literature'),
    ('The Count of Monte Cristo', 'art_literature'),
    ('Helena Bonham Carter', 'art_literature'),
    ('Terry Crews', 'art_literature'),
    ('Alexandra Grant', 'art_literature'),
    ('James Bond', 'art_literature'),
    ('Rhaenyra Targaryen', 'art_literature'),
    ('Jawaharlal Nehru', 'art_literature'),
    ('Harry Potter (film series)', 'art_literature'),
    ('Whalefall (novel)', 'art_literature'),
    ('Kenneth Branagh', 'art_literature'),
    ('Yesteryear (novel)', 'art_literature'),
    ('Communication', 'art_literature'),
    ("The Handmaid's Tale", 'art_literature'),
    ('Maggie Smith', 'art_literature'),
    ('Alan Rickman', 'art_literature'),
    ('Mount Rushmore', 'art_literature'),
    ('Agatha Christie', 'art_literature'),
    ('Bob Ross', 'art_literature'),
    ('House of Leaves', 'art_literature'),
    ('Brandon Sanderson', 'art_literature'),
    ('Blood Meridian', 'art_literature'),
    ('Sadako Yamamura', 'art_literature'),
    ('Lord of the Flies', 'art_literature'),
    ('Joseph Smith', 'art_literature'),
    ('The Winds of Winter', 'art_literature'),
    ('Richard Harris', 'art_literature'),
    ('The Vampire Lestat', 'art_literature'),
    ('Alien (franchise)', 'art_literature'),
    ('Jean-Michel Basquiat', 'art_literature'),
    ('Jason Isaacs', 'art_literature'),
    ('Harry Potter (TV series)', 'art_literature'),
    ('A Court of Thorns and Roses', 'art_literature'),
    ('Betty Mahmoody', 'art_literature'),
    ('Sam Raimi', 'art_literature'),
    ('The Backrooms', 'mythology_folklore'),
    ('Robin Hood', 'mythology_folklore'),
    ('Until Dawn', 'video_games'),
    ('Bermuda Triangle', 'mythology_folklore'),
    ('Moses', 'mythology_folklore'),
    ('Lucifer', 'mythology_folklore'),
    ('Bigfoot', 'mythology_folklore'),
    ('Loch Ness Monster', 'mythology_folklore'),
    ('Ragnar Lodbrok', 'mythology_folklore'),
    ('Nekomata', 'mythology_folklore'),
    ('Wendigo', 'mythology_folklore'),
    ('Jinn', 'mythology_folklore'),
    ('One Thousand and One Nights', 'mythology_folklore'),
    ('Ship of Theseus', 'mythology_folklore'),
    ('Momo Challenge hoax', 'mythology_folklore'),
    ('Hans Christian Andersen', 'mythology_folklore'),
    ('Slender Man', 'mythology_folklore'),
    ('Religion', 'mythology_folklore'),
    ('Pied Piper of Hamelin', 'mythology_folklore'),
    ('Brothers Grimm', 'mythology_folklore'),
    ('Befana', 'mythology_folklore'),
    ('Lady Godiva', 'mythology_folklore'),
    ('Rumpelstiltskin', 'mythology_folklore'),
    ('Baba Yaga', 'mythology_folklore'),
    ('Cinderella', 'mythology_folklore'),
    ('Golem', 'mythology_folklore'),
    ('Succubus', 'mythology_folklore'),
    ('Faust', 'mythology_folklore'),
    ('Chupacabra', 'mythology_folklore'),
    ("Hero's journey", 'mythology_folklore'),
    ('Kitsune', 'mythology_folklore'),
    ('Nimrod', 'mythology_folklore'),
    ('Jeff the Killer', 'mythology_folklore'),
    ('Mothman', 'mythology_folklore'),
    ("Will-o'-the-wisp", 'mythology_folklore'),
    ('Druid', 'mythology_folklore'),
    ('The Quarry (video game)', 'video_games'),
    ('David Grusch UFO whistleblower claims', 'mythology_folklore'),
    ('Zombie', 'mythology_folklore'),
    ('Reptilian humanoid', 'mythology_folklore'),
    ('Manatee', 'mythology_folklore'),
    ('Samson', 'mythology_folklore'),
    ('Yōkai', 'mythology_folklore'),
    ('Halloween', 'mythology_folklore'),
    ('Unicorn', 'mythology_folklore'),
    ('William Tell', 'mythology_folklore'),
    ('Yeti', 'mythology_folklore'),
    ('Drop bear', 'mythology_folklore'),
    ('Annabelle (doll)', 'mythology_folklore'),
    ('Santa Claus', 'mythology_folklore'),
    ('Paul Bunyan', 'mythology_folklore'),
    ('Grey alien', 'mythology_folklore'),
    ('Selkie', 'mythology_folklore'),
    ('Incubus', 'mythology_folklore'),
    ('Garden of Eden', 'mythology_folklore'),
    ('Feral child', 'mythology_folklore'),
    ('Griffin', 'mythology_folklore'),
    ('Holy Grail', 'mythology_folklore'),
    ('La Llorona', 'mythology_folklore'),
    ('Mephistopheles', 'mythology_folklore'),
    ('Abu Fanous', 'mythology_folklore'),
    ('Joseph Campbell', 'mythology_folklore'),
    ('Hell', 'mythology_folklore'),
    ('Aladdin', 'mythology_folklore'),
    ('Deal with the Devil', 'mythology_folklore'),
    ('Flying Dutchman', 'mythology_folklore'),
    ('Cú Chulainn', 'mythology_folklore'),
    ("Aesop's Fables", 'mythology_folklore'),
    ("Grimms' Fairy Tales", 'mythology_folklore'),
    ('Snow White', 'mythology_folklore'),
    ('Banshee', 'mythology_folklore'),
    ('The Little Mermaid', 'mythology_folklore'),
    ('Love Island USA', 'tv_shows'),
    ('Fullmetal Alchemist: Brotherhood', 'anime_manga'),
    ('Dragon Ball Z', 'anime_manga'),
    ('Bleach (manga)', 'anime_manga'),
    ('The Beatles', 'music'),
    ('Michael Jackson', 'music'),
    ('Taylor Swift', 'music'),
    ('Beyoncé', 'music'),
    ('Elvis Presley', 'music'),
    ('Madonna', 'music'),
    ('Queen (band)', 'music'),
    ('Pink Floyd', 'music'),
    ('Led Zeppelin', 'music'),
    ('Bob Dylan', 'music'),
    ('David Bowie', 'music'),
    ('Prince (musician)', 'music'),
    ('Whitney Houston', 'music'),
    ('Adele', 'music'),
    ('Drake (musician)', 'music'),
    ('Eminem', 'music'),
    ('Rihanna', 'music'),
    ('Lady Gaga', 'music'),
    ('Billie Eilish', 'music'),
    ('Bruno Mars', 'music'),
    ('Ed Sheeran', 'music'),
    ('The Rolling Stones', 'music'),
    ('Nirvana (band)', 'music'),
    ('Metallica', 'music'),
    ('Hip hop', 'music'),
    ('Jazz', 'music'),
    ('Classical music', 'music'),
    ('Rock music', 'music'),
    ('Pop music', 'music'),
    ('Bohemian Rhapsody', 'music'),
    ('Thriller (album)', 'music'),
    ('Abbey Road', 'music'),
    ('Music', 'music'),
    ('Guitar', 'music'),
    ('Piano', 'music'),
    ('Concert', 'music'),
    ('Grammy Awards', 'music'),
    ('Eurovision Song Contest', 'music'),
    ('Oliver Tree', 'music'),
    ('Anne Hathaway', 'music'),
    ('Dua Lipa', 'music'),
    ('Zendaya', 'music'),
    ('Shakira', 'music'),
    ('Olivia Rodrigo', 'music'),
    ('Jaafar Jackson', 'music'),
    ('Joe Jackson (talent manager)', 'music'),
    ('Tay Keith', 'music'),
    ('Nicholas Galitzine', 'music'),
    ('Jennifer Lopez', 'music'),
    ('Peabo Bryson', 'music'),
    ('Michael Johnston (actor)', 'music'),
    ('Zara Larsson', 'music'),
    ('Marilyn Monroe', 'music'),
    ('Alan Greenspan', 'music'),
    ('Clint Eastwood', 'music'),
    ('Jermaine Jackson', 'music'),
    ('Lisa Marie Presley', 'music'),
    ('Katy Perry', 'music'),
    ('Ella Langley', 'music'),
    ('Kim Kardashian', 'music'),
    ('Freddie Mercury', 'music'),
    ('Jackson family', 'music'),
    ('Keke Palmer', 'music'),
    ('Mel Brooks', 'music'),
    ("Shaquille O'Neal", 'music'),
    ('Paul McCartney', 'music'),
    ('Keanu Reeves', 'music'),
    ('XXXTentacion', 'music'),
    ('Janet Jackson', 'music'),
    ('Amy Adams', 'music'),
    ('Jelly Roll (singer)', 'music'),
    ('Ryan Gosling', 'music'),
    ('Melanie Martinez', 'music'),
    ('Kylie Minogue', 'music'),
    ('Scarlett Johansson', 'music'),
    ('XXX (Kendrick Lamar song)', 'music'),
    ('Alan Cumming', 'music'),
    ('Antonio Cipriano', 'music'),
    ('Robin Williams', 'music'),
    ('Zoë Kravitz', 'music'),
    ('Kanye West', 'music'),
    ('The Jackson 5', 'music'),
    ('Scary Movie', 'music'),
    ('Robert Smith (musician)', 'music'),
    ('Henry VIII', 'music'),
    ('Rod Stewart', 'music'),
    ('Hugh Jackman', 'music'),
    ('Idris Elba', 'music'),
    ('James Franco', 'music'),
    ('Nora Fatehi', 'music'),
    ('Meryl Streep', 'music'),
    ('Tito Jackson', 'music'),
    ('Sally Field', 'music'),
    ('Elliot Page', 'video_games'),
    ('Jon Bernthal', 'video_games'),
    ("Assassin's Creed", 'video_games'),
    ('Hayden Panettiere', 'video_games'),
    ('Intelligence artificielle', 'video_games'),
    ('Minka Kelly', 'video_games'),
    ('Yvonne Strahovski', 'video_games'),
    ('Richard Darbois', 'video_games'),
    ('Lucien Jean-Baptiste', 'video_games'),
    ('Clair Obscur: Expedition 33', 'video_games'),
    ('Grand Theft Auto: San Andreas', 'video_games'),
    ('Hans Zimmer', 'video_games'),
    ('Dorothée Pousséo', 'video_games'),
    ('Donald Reignoux', 'video_games'),
    ('The Amazing Digital Circus', 'video_games'),
    ('Squeezie', 'video_games'),
    ('Céline Monsarrat', 'video_games'),
    ('Lena Headey', 'video_games'),
    ('Emmanuel Curtil', 'video_games'),
    ('Jensen Ackles', 'video_games'),
    ('Kiefer Sutherland', 'video_games'),
    ('Destiny Eleven', 'video_games'),
    ('Nathan Fillion', 'video_games'),
    ('Bernard Alane', 'video_games'),
    ('Jean Pormanove', 'video_games'),
    ('Ron Perlman', 'video_games'),
    ('Will Yun Lee', 'video_games'),
    ('Adeline Chetail', 'video_games'),
    ('Lana et Lilly Wachowski', 'video_games'),
    ('Jacques Frantz', 'video_games'),
    ('Adrien Antoine', 'video_games'),
    ('Jean-Philippe Puymartin', 'video_games'),
    ('Christopher Lee', 'video_games'),
    ('Faker', 'video_games'),
    ('Clancy Brown', 'video_games'),
    ('Pokémon (série de jeux vidéo)', 'video_games'),
    ('Patrick Préjean', 'video_games'),
    ("Assassin's Creed Black Flag Resynced", 'video_games'),
    ('Inoxtag', 'video_games'),
    ('Michou (vidéaste)', 'video_games'),
    ('Féodor Atkine', 'video_games'),
    ('Grand Theft Auto IV', 'video_games'),
    ('ZA/UM', 'video_games'),
    ("Assassin's Creed IV Black Flag", 'video_games'),
    ('PlayStation 4', 'video_games'),
    ('Manon Azem', 'video_games'),
    ('Jérémie Covillault', 'video_games'),
    ('PlayStation 3', 'video_games'),
    ('Christophe Lemoine', 'video_games'),
    ('Alice David', 'video_games'),
    ('Roger Carel', 'video_games'),
    ('Liste des Pokémon', 'video_games'),
    ('Michelle Rodriguez (actrice)', 'video_games'),
    ('Sam Neill', 'tv_shows'),
    ('GIGN (mini-série)', 'tv_shows'),
    ('Inde Navarrette', 'tv_shows'),
    ('La Petite Maison dans la prairie', 'tv_shows'),
    ('Silo (série télévisée)', 'tv_shows'),
    ('Univers cinématographique Marvel', 'tv_shows'),
    ('Heroes', 'tv_shows'),
    ('Terence Hill', 'tv_shows'),
    ('John Leguizamo', 'tv_shows'),
    ('George Clooney', 'tv_shows'),
    ('Camping Paradis', 'tv_shows'),
    ("L'Été 36 (mini-série)", 'tv_shows'),
    ('Tout cela je te le donnerai', 'tv_shows'),
    ('Judith El Zein', 'tv_shows'),
    ("Avatar, le dernier maître de l'air", 'tv_shows'),
    ('Desperate Housewives', 'tv_shows'),
    ('Liste des épisodes de One Piece', 'tv_shows'),
    ('Jean Dujardin', 'tv_shows'),
    ('Urgences (série télévisée)', 'tv_shows'),
    ('Yellowstone (série télévisée)', 'tv_shows'),
    ('From', 'tv_shows'),
    ('Milly Alcock', 'tv_shows'),
    ('Bud Spencer', 'tv_shows'),
    ('Julia Roberts', 'tv_shows'),
    ('Alice Pol', 'tv_shows'),
    ('Shannen Doherty', 'tv_shows'),
    ('Rex, chien flic', 'tv_shows'),
    ('Mylène Demongeot', 'tv_shows'),
    ('Everwood', 'tv_shows'),
    ('Les Frères Scott', 'tv_shows'),
    ('O.P.J.', 'tv_shows'),
    ('Armie Hammer', 'tv_shows'),
    ('Catherine Alric', 'tv_shows'),
    ('Liste des épisodes de Camping Paradis', 'tv_shows'),
    ('Le Maître du Zodiaque', 'tv_shows'),
    ('The Walking Dead (série télévisée)', 'tv_shows'),
    ('Volodymyr Zelensky', 'tv_shows'),
    ('Happy Valley (série télévisée)', 'tv_shows'),
    ('Jessica Alba', 'tv_shows'),
    ('Alain Delon', 'tv_shows'),
    ('Zoey Deutch', 'tv_shows'),
    ('Saison 14 de Secret Story', 'tv_games'),
    ('Fort Boyard (jeu télévisé)', 'tv_games'),
    ('Cyril Féraud', 'tv_games'),
    ("N'oubliez pas les paroles !", 'tv_games'),
    ('Secret Story', 'tv_games'),
    ('Les Traîtres', 'tv_games'),
    ('Nagui', 'tv_games'),
    ('Les Douze Coups de midi', 'tv_games'),
    ('Saison 13 de Secret Story', 'tv_games'),
    ('Olivier Minne', 'tv_games'),
    ('André Bouchet', 'tv_games'),
    ('Koh-Lanta', 'tv_games'),
    ('Jean-Luc Reichmann', 'tv_games'),
    ('Jean-Pierre Foucault', 'tv_games'),
    ('Laurence Boccolini', 'tv_games'),
    ('Patrice Laffont', 'tv_games'),
    ("Vincent Lagaf'", 'tv_games'),
    ('Saison 13 de Star Academy', 'tv_games'),
    ('Saison 1 de Secret Story', 'tv_games'),
    ('Toy Story 4', 'anime_manga'),
    ('Jim Queen', 'anime_manga'),
    ('In Waves (film)', 'anime_manga'),
    ('Des Minions et des monstres', 'anime_manga'),
    ('Les Minions', 'anime_manga'),
    ("Les Maîtres de l'univers", 'anime_manga'),
    ("Liste des Classiques d'animation Disney", 'anime_manga'),
    ('Liste des films Pixar', 'anime_manga'),
    ('Tim Burton', 'anime_manga'),
    ('Musclor', 'anime_manga'),
    ('Les Simpson', 'anime_manga'),
    ('Pixar Animation Studios', 'anime_manga'),
    ('Le Tombeau des lucioles', 'anime_manga'),
    ('Rick et Morty', 'anime_manga'),
    ('Wes Anderson', 'anime_manga'),
    ('Arthur et les Minimoys (film)', 'anime_manga'),
    ('La Légende de Korra', 'anime_manga'),
    ('Walt Disney', 'anime_manga'),
    ('Le Roi lion', 'anime_manga'),
    ('Toy Story 2', 'anime_manga'),
    ('DreamWorks Animation', 'anime_manga'),
    ('Lucky Luke', 'anime_manga'),
    ('KPop Demon Hunters', 'anime_manga'),
    ('Albert Uderzo', 'anime_manga'),
    ("L'Âge de glace (série de films)", 'anime_manga'),
    ('Cars (film)', 'anime_manga'),
    ('Liste des épisodes de Bleach', 'anime_manga'),
    ('Scooby-Doo', 'anime_manga'),
    ("Bob l'éponge", 'anime_manga'),
    ('Pierre Coffin', 'anime_manga'),
    ('Club Dorothée', 'anime_manga'),
    ('Shrek (film)', 'anime_manga'),
    ('Liste des épisodes de Naruto', 'anime_manga'),
    ("Arcane (série d'animation)", 'anime_manga'),
    ("L'Odyssée (série télévisée d'animation)", 'anime_manga'),
    ('Moi, moche et méchant', 'anime_manga'),
    ('Totally Spies!', 'anime_manga'),
    ('Jumpers', 'anime_manga'),
    ("Les Douze Travaux d'Astérix", 'anime_manga'),
    ('Skeletor', 'anime_manga'),
    ('Lamine Yamal', 'sports'),
    ('Kylian Mbappé', 'sports'),
    ('Lionel Messi', 'sports'),
    ('Michael Olise', 'sports'),
    ('Coupe du monde de football', 'sports'),
    ('Gianni Infantino', 'sports'),
    ('Erling Haaland', 'sports'),
    ('Zinédine Zidane', 'sports'),
    ('Didier Deschamps', 'sports'),
    ('Cristiano Ronaldo', 'sports'),
    ('Aymeric Laporte', 'sports'),
    ('Équipe de France de football', 'sports'),
    ("Équipe d'Espagne de football", 'sports'),
    ('Tadej Pogačar', 'sports'),
    ('Lucas Digne', 'sports'),
    ('Ousmane Dembélé', 'sports'),
    ('Jude Bellingham', 'sports'),
    ('Rayan Cherki', 'sports'),
    ('Marc Cucurella', 'sports'),
    ('Leandro Paredes', 'sports'),
    ('Paul Seixas', 'sports'),
    ('Yannick Alléno', 'food_cuisine'),
    ('Philippe Etchebest', 'food_cuisine'),
    ('Julie Andrieu', 'food_cuisine'),
    ('Chimichurri', 'food_cuisine'),
    ('Chakchouka', 'food_cuisine'),
    ('Kéfir', 'food_cuisine'),
    ('Cyril Lignac', 'food_cuisine'),
    ('Zaatar', 'food_cuisine'),
    ('Red Bull (entreprise)', 'food_cuisine'),
    ('Halloumi', 'food_cuisine'),
    ('Skyr', 'food_cuisine'),
    ("Association amicale des amateurs d'andouillette authentique", 'food_cuisine'),
    ('Stracciatella (soupe)', 'food_cuisine'),
    ('Poutargue', 'food_cuisine'),
    ('Margarita (cocktail)', 'food_cuisine'),
    ('Tasty Crousty', 'food_cuisine'),
    ('Picon', 'food_cuisine'),
    ('Thiéboudiène', 'food_cuisine'),
    ('Salmorejo', 'food_cuisine'),
    ('Salade César', 'food_cuisine'),
    ('Salade niçoise', 'food_cuisine'),
    ('Maté', 'food_cuisine'),
    ('Häagen-Dazs', 'food_cuisine'),
    ('Poutine (plat)', 'food_cuisine'),
    ('Cauchemar en cuisine (France)', 'food_cuisine'),
    ('Jean Imbert (cuisinier)', 'food_cuisine'),
    ('Absinthe (spiritueux)', 'food_cuisine'),
    ('Welsh (plat)', 'food_cuisine'),
    ('Angostura (boisson)', 'food_cuisine'),
    ('Alain Ducasse', 'food_cuisine'),
    ('Anne-Sophie Pic', 'food_cuisine'),
    ('Fricadelle', 'food_cuisine'),
    ('Gin', 'food_cuisine'),
    ('Andouillette', 'food_cuisine'),
    ('Orangina', 'food_cuisine'),
    ('Magnum (marque)', 'food_cuisine'),
    ('Spiruline alimentaire', 'food_cuisine'),
    ('Tofu', 'food_cuisine'),
    ('Norbert Tarayre', 'food_cuisine'),
    ('Gombo', 'food_cuisine'),
    ('Kimchi', 'food_cuisine'),
    ('Paprika', 'food_cuisine'),
    ('Danone', 'food_cuisine'),
    ('Cognac (eau-de-vie)', 'food_cuisine'),
    ('Maigre (poisson)', 'food_cuisine'),
    ('Carbonade flamande', 'food_cuisine'),
    ('Focaccia', 'food_cuisine'),
    ('Quick (restauration)', 'food_cuisine'),
    ('Cachaça', 'food_cuisine'),
    ('Dame blanche (dessert)', 'food_cuisine'),
    ('Paul Bocuse', 'food_cuisine'),
    ('Le Menu', 'food_cuisine'),
    ('Negroni (cocktail)', 'food_cuisine'),
    ('Morue', 'food_cuisine'),
    ("Liste des pays par taux d'obésité", 'food_cuisine'),
    ('Yuzu', 'food_cuisine'),
    ('Pomme de terre', 'food_cuisine'),
    ('Kouign-amann', 'food_cuisine'),
    ('Tomate', 'food_cuisine'),
    ('Caïpirinha', 'food_cuisine'),
    ('Feta', 'food_cuisine'),
    ('Schweppes', 'food_cuisine'),
    ('Ceviche', 'food_cuisine'),
    ('Pitaya', 'food_cuisine'),
    ('Achillée millefeuille', 'food_cuisine'),
    ('Chouchen', 'food_cuisine'),
    ('Bicarbonate de sodium', 'food_cuisine'),
    ('Caponata', 'food_cuisine'),
    ('Auguste Escoffier', 'food_cuisine'),
    ('Miko (marque)', 'food_cuisine'),
    ('Vitello tonnato', 'food_cuisine'),
    ('Liste de légumes', 'food_cuisine'),
    ('Vodka', 'food_cuisine'),
    ('Pâtes à la carbonara', 'food_cuisine'),
    ('Bernard Loiseau', 'food_cuisine'),
    ('Maïs', 'food_cuisine'),
    ('Arancini', 'food_cuisine'),
    ('François Vatel', 'food_cuisine'),
    ('Limoncello', 'food_cuisine'),
    ('Maïté', 'food_cuisine'),
    ('Tarte tropézienne', 'food_cuisine'),
    ('Affogato', 'food_cuisine'),
    ('Yassa (plat)', 'food_cuisine'),
    ('Eau', 'food_cuisine'),
    ('Aligot', 'food_cuisine'),
    ('Lactalis', 'food_cuisine'),
    ('Sauce gribiche', 'food_cuisine'),
    ('Rakı', 'food_cuisine'),
    ('Brugnon', 'food_cuisine'),
    ('Piperade', 'food_cuisine'),
    ('Bouillabaisse', 'food_cuisine'),
    ('Œuf Benedict', 'food_cuisine'),
    ('Œuf de cent ans', 'food_cuisine'),
    ('Get 27', 'food_cuisine'),
    ('Vermouth', 'food_cuisine'),
    ('Juan Arbeláez', 'food_cuisine'),
    ('Tzatzíki', 'food_cuisine'),
    ('Taboulé', 'food_cuisine'),
    ('Tielle', 'food_cuisine'),
    ('Charles de Gaulle', 'history'),
    ('Napoléon Ier', 'history'),
    ('Louis XIV', 'history'),
    ('Maria Carolina de Bourbon des Deux-Siciles', 'history'),
    ('Philippe Pétain', 'history'),
    ("Jeanne d'Arc", 'history'),
    ('Franklin Delano Roosevelt', 'history'),
    ('Adolf Hitler', 'history'),
    ('Seconde Guerre mondiale', 'history'),
    ('Louis XV', 'history'),
    ('Toulouse', 'history'),
    ('Napoléon III', 'history'),
    ('Première Guerre mondiale', 'history'),
    ('Prise de la Bastille', 'history'),
    ('Louis XVI', 'history'),
    ('Shoah', 'history'),
    ("Guerre d'indépendance des États-Unis", 'history'),
    ('Catherine de Médicis', 'history'),
    ('Liste des monarques de France', 'history'),
    ('Jules César', 'history'),
    ('Marc Bloch', 'history'),
    ("Marie-Antoinette d'Autriche", 'history'),
    ('Gilbert du Motier de La Fayette', 'history'),
    ('Révolution française', 'history'),
    ('Catherine II', 'history'),
    ('Union européenne', 'history'),
    ('Charles Quint', 'history'),
    ('Maximilien de Robespierre', 'history'),
    ('Affaire Dreyfus', 'history'),
    ('Ibrahim Traoré', 'history'),
    ('Richard Cœur de Lion', 'history'),
    ('Empire ottoman', 'history'),
    ('Maison Plantagenêt', 'history'),
    ('Régime de Vichy', 'history'),
    ('Charles-Maurice de Talleyrand-Périgord', 'history'),
    ('Joséphine de Beauharnais', 'history'),
    ("Invasion de l'Ukraine par la Russie", 'history'),
    ('Royaume de France', 'history'),
    ('Philippe II Auguste', 'history'),
    ('François-Joseph Ier', 'history'),
    ('Saint-Empire romain germanique', 'history'),
    ('Nicolae Ceaușescu', 'history'),
    ('Jean Jaurès', 'history'),
    ('Commune de Paris', 'history'),
    ('Napoléon II', 'history'),
    ('Marc Aurèle', 'history'),
    ('La casa de papel', 'history'),
    ("Liste des monarques d'Angleterre", 'history'),
    ('Jean-Bedel Bokassa', 'history'),
    ('Germaine de Staël', 'history'),
    ('Génocide des Tutsi du Rwanda', 'history'),
    ('Grèce antique', 'history'),
    ('Fête de la Fédération', 'history'),
    ('Organisation des Nations unies', 'history'),
    ('Thomas Sankara', 'history'),
    ("Déclaration d'indépendance des États-Unis", 'history'),
    ("Organisation du traité de l'Atlantique nord", 'history'),
    ('Île de Noirmoutier', 'history'),
    ('Génocide de Srebrenica', 'history'),
    ('Auschwitz', 'history'),
    ('Mahomet', 'history'),
    ('Fernand de Magellan', 'history'),
    ('Babylone', 'history'),
    ('Massacre de la Saint-Barthélemy', 'history'),
    ('Département français', 'geography'),
    ('Gironde (département)', 'geography'),
    ('Liste des capitales du monde', 'geography'),
    ('Liste des pays du monde', 'geography'),
    ('Île Maurice', 'geography'),
    ('Mont Rushmore', 'geography'),
    ('Var (département)', 'geography'),
    ('Liste des pays par population', 'geography'),
    ('Corse', 'geography'),
    ('Melilla', 'geography'),
    ('La Réunion', 'geography'),
    ('États des États-Unis', 'geography'),
    ('Christophe Colomb', 'geography'),
    ('Région française', 'geography'),
    ('Québec', 'geography'),
    ('Ardèche (département)', 'geography'),
    ('Guadeloupe', 'geography'),
    ('Landes (département)', 'geography'),
    ('Waze', 'geography'),
    ('Gibraltar', 'geography'),
    ('Triangle des Bermudes', 'geography'),
    ('Danube', 'geography'),
    ('Nouvelle-Calédonie', 'geography'),
    ('Vendée (département)', 'geography'),
    ('Drôme (département)', 'geography'),
    ('Sahara occidental', 'geography'),
    ('Guyane', 'geography'),
    ('Îles Canaries', 'geography'),
    ('Creuse (département)', 'geography'),
    ('Polynésie française', 'geography'),
    ('Taïwan', 'geography'),
    ('Martinique', 'geography'),
    ('Espace Schengen', 'geography'),
    ('Mont Ventoux', 'geography'),
    ('Aveyron (département)', 'geography'),
    ('Mer Méditerranée', 'geography'),
    ('Cantal (département)', 'geography'),
    ('Seine-et-Marne', 'geography'),
    ("France d'outre-mer", 'geography'),
    ('Plateau de Millevaches', 'geography'),
    ("Provence-Alpes-Côte d'Azur", 'geography'),
    ('Mayotte', 'geography'),
    ('Afrique', 'geography'),
    ('Vosges (département)', 'geography'),
    ('Everest', 'geography'),
    ('Quercy', 'geography'),
    ('Cookie (informatique)', 'technology'),
    ('Gmail', 'technology'),
    ('C (langage)', 'technology'),
    ('Dark web', 'technology'),
    ('Céline Dept', 'technology'),
    ('Code QR', 'technology'),
    ('Microsoft Outlook', 'technology'),
    ('Théodort', 'technology'),
    ('Arthur Mensch', 'technology'),
    ('IPhone', 'technology'),
    ('Telegram (application)', 'technology'),
    ('Bill Gates', 'technology'),
    ('Mark Zuckerberg', 'technology'),
    ('Pavel Dourov', 'technology'),
    ('R (langage)', 'technology'),
    ('Canva', 'technology'),
    ('Ada Lovelace', 'technology'),
    ('Google Play', 'technology'),
    ('Dario Amodei', 'technology'),
    ('Google Traduction', 'technology'),
    ('Laurent Alexandre', 'technology'),
    ('Liste des codes HTTP', 'technology'),
    ('Swan & Néo', 'technology'),
    ('Yann Le Cun', 'technology'),
    ('Combinaisons de touche Alt', 'technology'),
    ('Capgemini', 'technology'),
    ('MacOS', 'technology'),
    ('Android', 'technology'),
    ('Signal (application)', 'technology'),
    ('Outlook.com', 'technology'),
    ('BarCamp', 'technology'),
    ('Hugging Face', 'technology'),
    ('Google (moteur de recherche)', 'technology'),
    ('Null', 'technology'),
    ('Interstellar', 'science_space'),
    ("Liste d'éclipses solaires", 'science_space'),
    ('Robert Oppenheimer', 'science_space'),
    ('Éclipse solaire', 'science_space'),
    ('Claudia Sheinbaum', 'science_space'),
    ('Système solaire', 'science_space'),
    ('Étienne Klein', 'science_space'),
    ('Terre', 'science_space'),
    ('Hectare', 'science_space'),
    ('Chat de Schrödinger', 'science_space'),
    ('Fata morgana (optique)', 'science_space'),
    ('Cumulonimbus', 'science_space'),
    ('Benjamin Franklin', 'science_space'),
    ('Galilée (savant)', 'science_space'),
    ('Soleil', 'science_space'),
    ("Machine d'Anticythère", 'science_space'),
    ('Lune', 'science_space'),
    ('Vénus (planète)', 'science_space'),
    ('Aristote', 'science_space'),
    ("Moment d'une force", 'science_space'),
    ('Blaise Pascal', 'science_space'),
    ('René Descartes', 'science_space'),
    ('Voie lactée', 'science_space'),
    ('Point de rosée', 'science_space'),
    ('Programme Apollo', 'science_space'),
    ('Eau lourde', 'science_space'),
    ('Paradoxe de Fermi', 'science_space'),
    ('Hélium', 'science_space'),
    ('Trou noir', 'science_space'),
    ('Irène Joliot-Curie', 'science_space'),
    ('Thomas Edison', 'science_space'),
    ('Cratère de Chicxulub', 'science_space'),
    ('Grande Ourse', 'science_space'),
    ('Entropie (thermodynamique)', 'science_space'),
    ('Pluton (planète naine)', 'science_space'),
    ('Pic du Midi de Bigorre', 'science_space'),
    ('Jupiter (planète)', 'science_space'),
    ('ITER', 'science_space'),
    ('Big Bang', 'science_space'),
    ('Lazare Carnot', 'science_space'),
    ('Odyssée', 'art_literature'),
    ('Sophie Brocas', 'art_literature'),
    ('Iliade', 'art_literature'),
    ('Hélène (mythologie)', 'art_literature'),
    ('Françoise Mallet-Joris', 'art_literature'),
    ('Homère', 'art_literature'),
    ('La Servante écarlate', 'art_literature'),
    ('Laura Ingalls Wilder', 'art_literature'),
    ('Les Trois Mousquetaires', 'art_literature'),
    ('Alexandre Dumas', 'art_literature'),
    ('Victor Hugo', 'art_literature'),
    ('George Sand', 'art_literature'),
    ('Romain Gary', 'art_literature'),
    ('Le Comte de Monte-Cristo', 'art_literature'),
    ('Sylvain Tesson', 'art_literature'),
    ('Albert Camus', 'art_literature'),
    ('Harlan Coben', 'art_literature'),
    ('Freida McFadden', 'art_literature'),
    ('Gabriel Matzneff', 'art_literature'),
    ('Amélie Nothomb', 'art_literature'),
    ('Roi Arthur', 'art_literature'),
    ('Émile Zola', 'art_literature'),
    ('Jules Verne', 'art_literature'),
    ('Stephen King', 'art_literature'),
    ('Marlène Jobert', 'art_literature'),
    ('Georges Pompidou', 'art_literature'),
    ('Marcel Pagnol', 'art_literature'),
    ('Pierre Lemaitre', 'art_literature'),
    ('Maxime Chattam', 'art_literature'),
    ('Arthur Rimbaud', 'art_literature'),
    ('Fred Vargas', 'art_literature'),
    ('Alain Soral', 'art_literature'),
    ('Gaël Faye', 'art_literature'),
    ('Honoré de Balzac', 'art_literature'),
    ('Colette', 'art_literature'),
    ('Louis-Ferdinand Céline', 'art_literature'),
    ('Rachel Khan', 'art_literature'),
    ('Antoine de Saint-Exupéry', 'art_literature'),
    ("L'Étranger", 'art_literature'),
    ('Franck Thilliez', 'art_literature'),
    ('André Malraux', 'art_literature'),
    ('Molière', 'art_literature'),
    ('Le Rouge et le Noir', 'art_literature'),
    ('Fiodor Dostoïevski', 'art_literature'),
    ('Personnages du Trône de fer', 'art_literature'),
    ('Les Misérables', 'art_literature'),
    ('Jean-Jacques Rousseau', 'art_literature'),
    ('Charles Consigny', 'art_literature'),
    ('Kavinsky', 'music'),
    ('Bonnie Tyler', 'music'),
    ('Barbara Butch', 'music'),
    ('Marie-Paule Belle', 'music'),
    ('Bad Bunny', 'music'),
    ('BTS (groupe)', 'music'),
    ('Lauren Bennett', 'music'),
    ('The Weeknd', 'music'),
    ('Bee Gees', 'music'),
    ("Shy'm", 'music'),
    ('Charles Aznavour', 'music'),
    ('Serge Lama', 'music'),
    ('Laurent Voulzy', 'music'),
    ('Guesch Patti', 'music'),
    ('XXL (chanson)', 'music'),
    ('System of a Down', 'music'),
    ('Helena Noguerra', 'music'),
    ('La Marseillaise', 'music'),
    ('ABBA', 'music'),
    ('Johnny Hallyday', 'music'),
    ('Jean-Jacques Goldman', 'music'),
    ('Hugues Aufray', 'music'),
    ('Mosimann', 'music'),
    ('Michel Sardou', 'music'),
    ('Alain Souchon', 'music'),
    ('Eva (chanteuse française)', 'music'),
    ('Dalida', 'music'),
    ('Gims', 'music'),
    ('Vanessa Paradis', 'music'),
    ('Justin Bieber', 'music'),
    ('Isabelle Adjani', 'music'),
    ('Amy Winehouse', 'music'),
    ('Theodora (chanteuse)', 'music'),
    ('Aya Nakamura', 'music'),
    ('Jérémy Frerot', 'music'),
    ('Gaëtan Roussel', 'music'),
    ('Alain Barrière', 'music'),
    ('Renaud', 'music'),
    ('Julien Clerc', 'music'),
    ('Jul (rappeur)', 'music'),
    ('La Fièvre du samedi soir', 'music'),
    ('Édith Piaf', 'music'),
    ('Philippe Katerine', 'music'),
    ('Barry Gibb', 'music'),
    ('Miki (artiste)', 'music'),
    ('Joe Dassin', 'music'),
    ('The Cure', 'music'),
    ('Cécile Cassel', 'music'),
    ('Charlotte Cardin', 'music'),
    ('Adèle Castillon', 'music'),
    ('Catherine Ringer', 'music'),
    ('Line Renaud', 'music'),
    ('Bertrand Cantat', 'music'),
    ('Quentin Dupieux', 'music'),
    ('Christopher Nolan', 'movies'),
    ('Ester Expósito', 'movies'),
    ('Tom Holland (acteur)', 'movies'),
    ('IMAX', 'movies'),
    ("Les Trois Mousquetaires : D'Artagnan", 'movies'),
    ('Matt Damon', 'movies'),
    ('Tomer Sisley', 'movies'),
    ('XXX (film)', 'movies'),
    ('Marc Messier', 'movies'),
    ('Penélope Cruz', 'movies'),
    ('Troie (film)', 'movies'),
    ('Javier Bardem', 'movies'),
    ('Timothée Chalamet', 'movies'),
    ('Les Trois Mousquetaires : Milady', 'movies'),
    ('Kaylee Hottle', 'movies'),
    ('Simon Abkarian', 'movies'),
    ('Patrick Dewaere', 'movies'),
    ('La mariée était en noir (film)', 'movies'),
    ('Charlize Theron', 'movies'),
    ('Evil Dead Burn', 'movies'),
    ('Eva Green', 'movies'),
    ('Millie Bobby Brown', 'movies'),
    ('Spider-Man (série de films)', 'movies'),
    ('Le Boucher', 'movies'),
    ('Avengers: Doomsday', 'movies'),
    ("Lupita Nyong'o", 'movies'),
    ('Brad Pitt', 'movies'),
    ('Mortelle Randonnée (film)', 'movies'),
    ('Lyna Khoudri', 'movies'),
    ('Bruce Willis', 'movies'),
    ('Backrooms', 'movies'),
    ('Benny Safdie', 'movies'),
    ('Catherine Davydzenka', 'movies'),
    ('Jean-Marie Bigard', 'movies'),
    ('John Travolta', 'movies'),
    ('Nastassja Kinski', 'movies'),
    ('Soudain seuls', 'movies'),
    ('La nuit nous appartient', 'movies'),
    ('Stéphane Audran', 'movies'),
    ('Robert Pattinson', 'movies'),
    ('Tom Cruise', 'movies'),
    ('Disclosure Day', 'movies'),
    ('Ulysse', 'mythology_folklore'),
    ('Guerre de Troie', 'mythology_folklore'),
    ('Agamemnon', 'mythology_folklore'),
    ('Calypso', 'mythology_folklore'),
    ('Circé', 'mythology_folklore'),
    ('Lestrygons', 'mythology_folklore'),
    ('Troie', 'mythology_folklore'),
    ('Achille', 'mythology_folklore'),
    ('Télémaque', 'mythology_folklore'),
    ('Sinon', 'mythology_folklore'),
    ('Ménélas', 'mythology_folklore'),
    ('Clytemnestre', 'mythology_folklore'),
    ('Cheval de Troie', 'mythology_folklore'),
    ('Nausicaa', 'mythology_folklore'),
    ('Polyphème', 'mythology_folklore'),
]
